#!/usr/bin/python
#
# THIS FILE IS AUTOGENERATED BY THE ANSIBLE MODULE GENERATOR - DO NOT EDIT
#
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.community.generic.plugins.module_utils.waldur.facts_runner import (
    FactsRunner,
)
from waldur_api_client.api.openstack_instances import openstack_instances_list
from waldur_api_client.api.openstack_instances import openstack_instances_retrieve
from waldur_api_client.api.projects import projects_list
from waldur_api_client.api.projects import projects_retrieve

ANSIBLE_METADATA = {
    "metadata_version": "1.1",
    "status": ["preview"],
    "supported_by": "OpenNode",
}

DOCUMENTATION = """
---
module: community.generic.openstack_instance_facts
short_description: Get an existing openstack instance.
version_added: '0.1'
description:
- Get an existing openstack instance.
requirements:
- python = 3.11
- waldur-api-client
options:
  access_token:
    description: An access token.
    required: true
    type: str
    no_log: true
  api_url:
    description: Fully qualified URL to the API.
    required: true
    type: str
  name:
    type: str
    required: true
    description: The name or UUID of the openstack instance.
  project:
    type: str
    required: true
    description: The name or UUID of the project.

"""

EXAMPLES = """
- name: Get a openstack instance facts
  hosts: localhost
  tasks:
  - name: Get a openstack instance
    community.generic.openstack_instance_facts:
      access_token: b83557fd8e2066e98f27dee8f3b3433cdc4183ce
      api_url: https://waldur.example.com:8000/api
      name: Openstack_instance Name or UUID
      project: Project Name or UUID

"""

RETURN = """
resource:
  description: A dictionary describing the found openstack_instance.
  type: dict
  returned: on success
  contains:
    url:
      description: url
      type: str
      returned: always
      sample: https://api.example.com/api/resource/...
    uuid:
      description: uuid
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    name:
      description: name
      type: str
      returned: always
      sample: string_value
    description:
      description: description
      type: str
      returned: always
      sample: string_value
    service_name:
      description: service name
      type: str
      returned: always
      sample: string_value
    service_settings:
      description: service settings
      type: str
      returned: always
      sample: https://api.example.com/api/resource/...
    service_settings_uuid:
      description: service settings uuid
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    service_settings_state:
      description: service settings state
      type: str
      returned: always
      sample: string_value
    service_settings_error_message:
      description: service settings error message
      type: str
      returned: always
      sample: string_value
    project:
      description: project
      type: str
      returned: always
      sample: https://api.example.com/api/resource/...
    project_name:
      description: project name
      type: str
      returned: always
      sample: string_value
    project_uuid:
      description: project uuid
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    customer:
      description: customer
      type: str
      returned: always
      sample: https://api.example.com/api/resource/...
    customer_name:
      description: customer name
      type: str
      returned: always
      sample: string_value
    customer_native_name:
      description: customer native name
      type: str
      returned: always
      sample: string_value
    customer_abbreviation:
      description: customer abbreviation
      type: str
      returned: always
      sample: string_value
    error_message:
      description: error message
      type: str
      returned: always
      sample: string_value
    error_traceback:
      description: error traceback
      type: str
      returned: always
      sample: string_value
    resource_type:
      description: resource type
      type: str
      returned: always
      sample: string_value
    state:
      description: ''
      type: str
      returned: always
      sample: string_value
    created:
      description: created
      type: str
      returned: always
      sample: '2023-10-01T12:00:00Z'
    modified:
      description: modified
      type: str
      returned: always
      sample: '2023-10-01T12:00:00Z'
    backend_id:
      description: backend id
      type: str
      returned: always
      sample: string_value
    access_url:
      description: access url
      type: str
      returned: always
      sample: string_value
    start_time:
      description: start time
      type: str
      returned: always
      sample: '2023-10-01T12:00:00Z'
    cores:
      description: Number of cores in a VM
      type: int
      returned: always
      sample: 123
    ram:
      description: Memory size in MiB
      type: int
      returned: always
      sample: 123
    disk:
      description: Disk size in MiB
      type: int
      returned: always
      sample: 123
    min_ram:
      description: Minimum memory size in MiB
      type: int
      returned: always
      sample: 123
    min_disk:
      description: Minimum disk size in MiB
      type: int
      returned: always
      sample: 123
    user_data:
      description: Additional data that will be added to instance on provisioning
      type: str
      returned: always
      sample: string_value
    external_ips:
      description: external ips
      type: list
      returned: always
      sample: null
    internal_ips:
      description: internal ips
      type: list
      returned: always
      sample: null
    latitude:
      description: latitude
      type: float
      returned: always
      sample: 123.45
    longitude:
      description: longitude
      type: float
      returned: always
      sample: 123.45
    key_name:
      description: key name
      type: str
      returned: always
      sample: string_value
    key_fingerprint:
      description: key fingerprint
      type: str
      returned: always
      sample: string_value
    image_name:
      description: image name
      type: str
      returned: always
      sample: string_value
    flavor_disk:
      description: Flavor disk size in MiB
      type: int
      returned: always
      sample: 123
    flavor_name:
      description: flavor name
      type: str
      returned: always
      sample: string_value
    volumes:
      description: volumes
      type: list
      returned: always
      sample: null
      contains:
        url:
          description: url
          type: str
          returned: always
          sample: https://api.example.com/api/resource/...
        uuid:
          description: uuid
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        name:
          description: name
          type: str
          returned: always
          sample: string_value
        image_name:
          description: image name
          type: str
          returned: always
          sample: string_value
        state:
          description: state
          type: str
          returned: always
          sample: string_value
        bootable:
          description: bootable
          type: bool
          returned: always
          sample: true
        size:
          description: Size in MiB
          type: int
          returned: always
          sample: 123
        device:
          description: Name of volume as instance device e.g. /dev/vdb.
          type: str
          returned: always
          sample: My Resource Name
        resource_type:
          description: resource type
          type: str
          returned: always
          sample: string_value
        type:
          description: type
          type: str
          returned: always
          sample: https://api.example.com/api/resource/...
        type_name:
          description: type name
          type: str
          returned: always
          sample: string_value
        marketplace_resource_uuid:
          description: marketplace resource uuid
          type: str
          returned: always
          sample: string_value
    security_groups:
      description: security groups
      type: list
      returned: always
      sample: null
      contains:
        url:
          description: url
          type: str
          returned: always
          sample: https://api.example.com/api/resource/...
        name:
          description: name
          type: str
          returned: always
          sample: string_value
        rules:
          description: rules
          type: list
          returned: always
          sample: null
          contains:
            ethertype:
              description: ''
              type: str
              returned: always
              sample: string_value
            direction:
              description: ''
              type: str
              returned: always
              sample: string_value
            protocol:
              description: protocol
              type: str
              returned: always
              sample: null
            from_port:
              description: from port
              type: int
              returned: always
              sample: 123
            to_port:
              description: to port
              type: int
              returned: always
              sample: 123
            cidr:
              description: cidr
              type: str
              returned: always
              sample: string_value
            description:
              description: description
              type: str
              returned: always
              sample: string_value
            remote_group_name:
              description: remote group name
              type: str
              returned: always
              sample: string_value
            remote_group_uuid:
              description: remote group uuid
              type: str
              returned: always
              sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
            id:
              description: id
              type: int
              returned: always
              sample: 123
        description:
          description: description
          type: str
          returned: always
          sample: string_value
        state:
          description: state
          type: str
          returned: always
          sample: string_value
    server_group:
      description: ''
      type: dict
      returned: always
      sample: null
      contains:
        url:
          description: url
          type: str
          returned: always
          sample: https://api.example.com/api/resource/...
        name:
          description: name
          type: str
          returned: always
          sample: string_value
        policy:
          description: ''
          type: str
          returned: always
          sample: string_value
        state:
          description: state
          type: str
          returned: always
          sample: string_value
    floating_ips:
      description: floating ips
      type: list
      returned: always
      sample: null
      contains:
        url:
          description: url
          type: str
          returned: always
          sample: https://api.example.com/api/resource/...
        uuid:
          description: uuid
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        address:
          description: address
          type: str
          returned: always
          sample: string_value
        port_fixed_ips:
          description: port fixed ips
          type: list
          returned: always
          sample: null
          contains:
            ip_address:
              description: ip address
              type: str
              returned: always
              sample: string_value
            subnet_id:
              description: subnet id
              type: str
              returned: always
              sample: string_value
        port_mac_address:
          description: port mac address
          type: str
          returned: always
          sample: string_value
        subnet:
          description: subnet
          type: str
          returned: always
          sample: https://api.example.com/api/resource/...
        subnet_uuid:
          description: subnet uuid
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        subnet_name:
          description: subnet name
          type: str
          returned: always
          sample: string_value
        subnet_description:
          description: subnet description
          type: str
          returned: always
          sample: string_value
        subnet_cidr:
          description: subnet cidr
          type: str
          returned: always
          sample: string_value
    ports:
      description: ports
      type: list
      returned: always
      sample: null
      contains:
        url:
          description: url
          type: str
          returned: always
          sample: https://api.example.com/api/resource/...
        fixed_ips:
          description: fixed ips
          type: list
          returned: always
          sample: null
          contains:
            ip_address:
              description: ip address
              type: str
              returned: always
              sample: string_value
            subnet_id:
              description: subnet id
              type: str
              returned: always
              sample: string_value
        mac_address:
          description: mac address
          type: str
          returned: always
          sample: string_value
        subnet:
          description: subnet
          type: str
          returned: always
          sample: https://api.example.com/api/resource/...
        subnet_uuid:
          description: subnet uuid
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        subnet_name:
          description: subnet name
          type: str
          returned: always
          sample: string_value
        subnet_description:
          description: subnet description
          type: str
          returned: always
          sample: string_value
        subnet_cidr:
          description: subnet cidr
          type: str
          returned: always
          sample: string_value
        allowed_address_pairs:
          description: allowed address pairs
          type: list
          returned: always
          sample: null
          contains:
            mac_address:
              description: mac address
              type: str
              returned: always
              sample: string_value
        device_id:
          description: device id
          type: str
          returned: always
          sample: string_value
        device_owner:
          description: device owner
          type: str
          returned: always
          sample: string_value
        security_groups:
          description: security groups
          type: list
          returned: always
          sample: null
          contains:
            url:
              description: url
              type: str
              returned: always
              sample: https://api.example.com/api/resource/...
            uuid:
              description: uuid
              type: str
              returned: always
              sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
            name:
              description: name
              type: str
              returned: always
              sample: string_value
            description:
              description: description
              type: str
              returned: always
              sample: string_value
            service_name:
              description: service name
              type: str
              returned: always
              sample: string_value
            service_settings:
              description: service settings
              type: str
              returned: always
              sample: https://api.example.com/api/resource/...
            service_settings_uuid:
              description: service settings uuid
              type: str
              returned: always
              sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
            service_settings_state:
              description: service settings state
              type: str
              returned: always
              sample: string_value
            service_settings_error_message:
              description: service settings error message
              type: str
              returned: always
              sample: string_value
            project:
              description: project
              type: str
              returned: always
              sample: https://api.example.com/api/resource/...
            project_name:
              description: project name
              type: str
              returned: always
              sample: string_value
            project_uuid:
              description: project uuid
              type: str
              returned: always
              sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
            customer:
              description: customer
              type: str
              returned: always
              sample: https://api.example.com/api/resource/...
            customer_name:
              description: customer name
              type: str
              returned: always
              sample: string_value
            customer_native_name:
              description: customer native name
              type: str
              returned: always
              sample: string_value
            customer_abbreviation:
              description: customer abbreviation
              type: str
              returned: always
              sample: string_value
            error_message:
              description: error message
              type: str
              returned: always
              sample: string_value
            error_traceback:
              description: error traceback
              type: str
              returned: always
              sample: string_value
            resource_type:
              description: resource type
              type: str
              returned: always
              sample: string_value
            state:
              description: ''
              type: str
              returned: always
              sample: string_value
            created:
              description: created
              type: str
              returned: always
              sample: '2023-10-01T12:00:00Z'
            modified:
              description: modified
              type: str
              returned: always
              sample: '2023-10-01T12:00:00Z'
            backend_id:
              description: backend id
              type: str
              returned: always
              sample: string_value
            access_url:
              description: access url
              type: str
              returned: always
              sample: string_value
            tenant:
              description: tenant
              type: str
              returned: always
              sample: https://api.example.com/api/resource/...
            tenant_name:
              description: tenant name
              type: str
              returned: always
              sample: string_value
            tenant_uuid:
              description: tenant uuid
              type: str
              returned: always
              sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
            rules:
              description: rules
              type: list
              returned: always
              sample: null
              contains:
                ethertype:
                  description: ''
                  type: str
                  returned: always
                  sample: string_value
                direction:
                  description: ''
                  type: str
                  returned: always
                  sample: string_value
                protocol:
                  description: protocol
                  type: str
                  returned: always
                  sample: null
                from_port:
                  description: from port
                  type: int
                  returned: always
                  sample: 123
                to_port:
                  description: to port
                  type: int
                  returned: always
                  sample: 123
                cidr:
                  description: cidr
                  type: str
                  returned: always
                  sample: string_value
                description:
                  description: description
                  type: str
                  returned: always
                  sample: string_value
                remote_group_name:
                  description: remote group name
                  type: str
                  returned: always
                  sample: string_value
                remote_group_uuid:
                  description: remote group uuid
                  type: str
                  returned: always
                  sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
                id:
                  description: id
                  type: int
                  returned: always
                  sample: 123
                remote_group:
                  description: remote group
                  type: str
                  returned: always
                  sample: https://api.example.com/api/resource/...
            marketplace_offering_uuid:
              description: marketplace offering uuid
              type: str
              returned: always
              sample: string_value
            marketplace_offering_name:
              description: marketplace offering name
              type: str
              returned: always
              sample: string_value
            marketplace_offering_plugin_options:
              description: marketplace offering plugin options
              type: dict
              returned: always
              sample: null
            marketplace_category_uuid:
              description: marketplace category uuid
              type: str
              returned: always
              sample: string_value
            marketplace_category_name:
              description: marketplace category name
              type: str
              returned: always
              sample: string_value
            marketplace_resource_uuid:
              description: marketplace resource uuid
              type: str
              returned: always
              sample: string_value
            marketplace_plan_uuid:
              description: marketplace plan uuid
              type: str
              returned: always
              sample: string_value
            marketplace_resource_state:
              description: marketplace resource state
              type: str
              returned: always
              sample: string_value
            is_usage_based:
              description: is usage based
              type: bool
              returned: always
              sample: true
            is_limit_based:
              description: is limit based
              type: bool
              returned: always
              sample: true
    availability_zone:
      description: availability zone
      type: str
      returned: always
      sample: https://api.example.com/api/resource/...
    availability_zone_name:
      description: availability zone name
      type: str
      returned: always
      sample: string_value
    connect_directly_to_external_network:
      description: connect directly to external network
      type: bool
      returned: always
      sample: true
    runtime_state:
      description: runtime state
      type: str
      returned: always
      sample: string_value
    action:
      description: action
      type: str
      returned: always
      sample: string_value
    action_details:
      description: action details
      type: str
      returned: always
      sample: null
    tenant_uuid:
      description: tenant uuid
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    hypervisor_hostname:
      description: hypervisor hostname
      type: str
      returned: always
      sample: string_value
    tenant:
      description: tenant
      type: str
      returned: always
      sample: https://api.example.com/api/resource/...
    external_address:
      description: external address
      type: list
      returned: always
      sample: null
    rancher_cluster:
      description: ''
      type: dict
      returned: always
      sample: null
      contains:
        uuid:
          description: uuid
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        name:
          description: name
          type: str
          returned: always
          sample: string_value
        marketplace_uuid:
          description: marketplace uuid
          type: str
          returned: always
          sample: string_value
    marketplace_offering_uuid:
      description: marketplace offering uuid
      type: str
      returned: always
      sample: string_value
    marketplace_offering_name:
      description: marketplace offering name
      type: str
      returned: always
      sample: string_value
    marketplace_offering_plugin_options:
      description: marketplace offering plugin options
      type: dict
      returned: always
      sample: null
    marketplace_category_uuid:
      description: marketplace category uuid
      type: str
      returned: always
      sample: string_value
    marketplace_category_name:
      description: marketplace category name
      type: str
      returned: always
      sample: string_value
    marketplace_resource_uuid:
      description: marketplace resource uuid
      type: str
      returned: always
      sample: string_value
    marketplace_plan_uuid:
      description: marketplace plan uuid
      type: str
      returned: always
      sample: string_value
    marketplace_resource_state:
      description: marketplace resource state
      type: str
      returned: always
      sample: string_value
    is_usage_based:
      description: is usage based
      type: bool
      returned: always
      sample: true
    is_limit_based:
      description: is limit based
      type: bool
      returned: always
      sample: true

"""

ARGUMENT_SPEC = {
    "access_token": {
        "description": "An access token.",
        "required": True,
        "type": "str",
        "no_log": True,
    },
    "api_url": {
        "description": "Fully qualified URL to the API.",
        "required": True,
        "type": "str",
    },
    "name": {"type": "str", "required": True},
    "project": {"type": "str", "required": True},
}

RUNNER_CONTEXT = {
    "module_type": "facts",
    "resource_type": "openstack_instance",
    "list_func": openstack_instances_list,
    "retrieve_func": openstack_instances_retrieve,
    "identifier_param": "name",
    "context_resolvers": {
        "project": {
            "list_func": projects_list,
            "retrieve_func": projects_retrieve,
            "error_message": "Project '{value}' not found.",
            "filter_key": "project_uuid",
        },
    },
}


def main():
    """Main execution entrypoint for the Ansible module."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )
    runner = FactsRunner(module, RUNNER_CONTEXT)
    runner.run()


if __name__ == "__main__":
    main()
