#!/usr/bin/python
#
# THIS FILE IS AUTOGENERATED BY THE ANSIBLE MODULE GENERATOR - DO NOT EDIT
#
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.waldur.marketplace.plugins.module_utils.waldur.facts_runner import (
    FactsRunner,
)

ANSIBLE_METADATA = {
    "metadata_version": "1.1",
    "status": ["preview"],
    "supported_by": "OpenNode",
}

DOCUMENTATION = """
---
module: offering_facts
short_description: Get facts about a specific offering
description: ''
author: Waldur Team
options:
  access_token:
    description: An access token.
    required: true
    type: str
    no_log: true
  api_url:
    description: Fully qualified URL to the API.
    required: true
    type: str
  name:
    description: The name or UUID of the offering.
    type: str
    required: true
  customer:
    description: The name or UUID of the parent customer.
    type: str
    required: false
  accessible_via_calls:
    description: Accessible via calls
    type: bool
    required: false
  allowed_customer_uuid:
    description: Allowed customer UUID
    type: str
    required: false
  attributes:
    description: Offering attributes (JSON)
    type: str
    required: false
  billable:
    description: Billable
    type: bool
    required: false
  can_create_offering_user:
    description: Filter by can create offering user.
    type: bool
    required: false
  category_group_uuid:
    description: Category group UUID
    type: str
    required: false
  category_uuid:
    description: Category UUID
    type: str
    required: false
  created:
    description: Created after
    type: str
    required: false
  description:
    description: Description contains
    type: str
    required: false
  has_active_terms_of_service:
    description: Has Active Terms of Service
    type: bool
    required: false
  has_terms_of_service:
    description: Has Terms of Service
    type: bool
    required: false
  keyword:
    description: Keyword
    type: str
    required: false
  modified:
    description: Modified after
    type: str
    required: false
  organization_group_uuid:
    description: Organization group UUID
    type: list
    required: false
    elements: str
  parent_uuid:
    description: Parent offering UUID
    type: str
    required: false
  project_uuid:
    description: Project UUID
    type: str
    required: false
  query:
    description: Search by offering name, slug or description
    type: str
    required: false
  resource_customer_uuid:
    description: Resource customer UUID
    type: str
    required: false
  resource_project_uuid:
    description: Resource project UUID
    type: str
    required: false
  scope_uuid:
    description: Scope UUID
    type: str
    required: false
  service_manager_uuid:
    description: Service manager UUID
    type: str
    required: false
  shared:
    description: Shared
    type: bool
    required: false
  state:
    description: Offering state
    type: list
    required: false
    elements: str
    choices:
    - Active
    - Archived
    - Draft
    - Paused
  type:
    description: Offering type
    type: list
    required: false
    elements: str
  user_has_consent:
    description: User Has Consent
    type: bool
    required: false
  user_has_offering_user:
    description: User Has Offering User
    type: bool
    required: false
  uuid_list:
    description: Comma-separated offering UUIDs
    type: str
    required: false
requirements:
- python >= 3.11

"""

EXAMPLES = """
- name: Retrieve and print facts about offerings
  hosts: localhost
  tasks:
  - name: Get facts about a specific offering
    waldur.marketplace.offering_facts:
      name: My Resource Name
      customer: Customer name or UUID
      access_token: b83557fd8e2066e98f27dee8f3b3433cdc4183ce
      api_url: https://waldur.example.com
    register: resource_info
  - name: Print the retrieved resource facts
    ansible.builtin.debug:
      var: resource_info.offerings

"""

RETURN = """
resource:
  description: A dictionary representing the facts of a single offering.
  type: dict
  returned: on success
  contains:
    url:
      description: URL URL
      type: str
      returned: always
      sample: https://api.example.com/api/url/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    uuid:
      description: UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    created:
      description: Created
      type: str
      returned: always
      sample: '2023-10-01T12:00:00Z'
    name:
      description: Name
      type: str
      returned: always
      sample: My-Awesome-offering
    slug:
      description: Slug
      type: str
      returned: always
      sample: string-value
    description:
      description: Description
      type: str
      returned: always
      sample: A sample description created by Ansible.
    full_description:
      description: Full description
      type: str
      returned: always
      sample: string-value
    privacy_policy_link:
      description: Privacy policy link URL
      type: str
      returned: always
      sample: https://api.example.com/api/privacy-policy-link/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    access_url:
      description: Publicly accessible offering access URL
      type: str
      returned: always
      sample: https://api.example.com/api/access-url/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    endpoints:
      description: A list of endpoints items.
      type: list
      returned: always
      sample: []
      contains:
        uuid:
          description: UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        name:
          description: Name
          type: str
          returned: always
          sample: My-Awesome-offering
        url:
          description: URL
          type: str
          returned: always
          sample: string-value
    software_catalogs:
      description: A list of software catalogs items.
      type: list
      returned: always
      sample: []
      contains:
        uuid:
          description: UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        catalog:
          description: Catalog
          type: dict
          returned: always
          sample: {}
          contains:
            uuid:
              description: UUID
              type: str
              returned: always
              sample: string-value
            name:
              description: Name
              type: str
              returned: always
              sample: My-Awesome-offering
            version:
              description: Version
              type: str
              returned: always
              sample: string-value
            description:
              description: Description
              type: str
              returned: always
              sample: A sample description created by Ansible.
        enabled_cpu_family:
          description: 'List of enabled CPU families: [''x86_64'', ''aarch64'']'
          type: str
          returned: always
          sample: null
        enabled_cpu_microarchitectures:
          description: 'List of enabled CPU microarchitectures: [''generic'', ''zen3'']'
          type: str
          returned: always
          sample: null
        package_count:
          description: Package count
          type: int
          returned: always
          sample: 123
        partition:
          description: Partition
          type: dict
          returned: always
          sample: {}
          contains:
            uuid:
              description: UUID
              type: str
              returned: always
              sample: string-value
            partition_name:
              description: Partition name
              type: str
              returned: always
              sample: string-value
            priority_tier:
              description: Priority tier
              type: int
              returned: always
              sample: 123
            qos:
              description: Qos
              type: str
              returned: always
              sample: string-value
    partitions:
      description: A list of partitions items.
      type: list
      returned: always
      sample: []
      contains:
        uuid:
          description: UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        partition_name:
          description: Name of the SLURM partition
          type: str
          returned: always
          sample: string-value
        cpu_bind:
          description: Default task binding policy (SLURM cpu_bind)
          type: int
          returned: always
          sample: 123
        def_cpu_per_gpu:
          description: Default CPUs allocated per GPU
          type: int
          returned: always
          sample: 123
        max_cpus_per_node:
          description: Maximum allocated CPUs per node
          type: int
          returned: always
          sample: 123
        max_cpus_per_socket:
          description: Maximum allocated CPUs per socket
          type: int
          returned: always
          sample: 123
        def_mem_per_cpu:
          description: Default memory per CPU in MB
          type: int
          returned: always
          sample: 123
        def_mem_per_gpu:
          description: Default memory per GPU in MB
          type: int
          returned: always
          sample: 123
        def_mem_per_node:
          description: Default memory per node in MB
          type: int
          returned: always
          sample: 123
        max_mem_per_cpu:
          description: Maximum memory per CPU in MB
          type: int
          returned: always
          sample: 123
        max_mem_per_node:
          description: Maximum memory per node in MB
          type: int
          returned: always
          sample: 123
        default_time:
          description: Default time limit in minutes
          type: int
          returned: always
          sample: 123
        max_time:
          description: Maximum time limit in minutes
          type: int
          returned: always
          sample: 123
        grace_time:
          description: Preemption grace time in seconds
          type: int
          returned: always
          sample: 123
        max_nodes:
          description: Maximum nodes per job
          type: int
          returned: always
          sample: 123
        min_nodes:
          description: Minimum nodes per job
          type: int
          returned: always
          sample: 123
        exclusive_topo:
          description: Exclusive topology access required
          type: bool
          returned: always
          sample: true
        exclusive_user:
          description: Exclusive user access required
          type: bool
          returned: always
          sample: true
        priority_tier:
          description: Priority tier for scheduling and preemption
          type: int
          returned: always
          sample: 123
        qos:
          description: Quality of Service (QOS) name
          type: str
          returned: always
          sample: string-value
        req_resv:
          description: Require reservation for job allocation
          type: bool
          returned: always
          sample: true
    roles:
      description: A list of roles items.
      type: list
      returned: always
      sample: []
      contains:
        uuid:
          description: UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        name:
          description: Name
          type: str
          returned: always
          sample: My-Awesome-offering
        url:
          description: URL URL
          type: str
          returned: always
          sample: https://api.example.com/api/url/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    customer:
      description: Customer URL
      type: str
      returned: always
      sample: https://api.example.com/api/customer/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    customer_uuid:
      description: Customer UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    customer_name:
      description: Customer name
      type: str
      returned: always
      sample: Big Corp Inc.
    project:
      description: Project URL
      type: str
      returned: always
      sample: https://api.example.com/api/project/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    project_uuid:
      description: Project UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    project_name:
      description: Project name
      type: str
      returned: always
      sample: Internal Research Project
    category:
      description: Category URL
      type: str
      returned: always
      sample: https://api.example.com/api/category/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    category_uuid:
      description: Category UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    category_title:
      description: Category title
      type: str
      returned: always
      sample: string-value
    attributes:
      description: Attributes
      type: dict
      returned: always
      sample: {}
    options:
      description: Options
      type: str
      returned: always
      sample: null
    resource_options:
      description: Resource options
      type: str
      returned: always
      sample: null
    components:
      description: A list of components items.
      type: list
      returned: always
      sample: []
      contains:
        uuid:
          description: UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        billing_type:
          description: Billing type
          type: str
          returned: always
          sample: fixed
        type:
          description: Unique internal name of the measured unit, for example floating_ip.
          type: str
          returned: always
          sample: string-value
        name:
          description: Display name for the measured unit, for example, Floating IP.
          type: str
          returned: always
          sample: My-Awesome-offering
        description:
          description: Description
          type: str
          returned: always
          sample: A sample description created by Ansible.
        measured_unit:
          description: Unit of measurement, for example, GB.
          type: str
          returned: always
          sample: string-value
        unit_factor:
          description: The conversion factor from backend units to measured_unit
          type: int
          returned: always
          sample: 123
        limit_period:
          description: Limit period
          type: str
          returned: always
          sample: null
        limit_amount:
          description: Limit amount
          type: int
          returned: always
          sample: 123
        article_code:
          description: Article code
          type: str
          returned: always
          sample: string-value
        max_value:
          description: Max value
          type: int
          returned: always
          sample: 123
        min_value:
          description: Min value
          type: int
          returned: always
          sample: 123
        max_available_limit:
          description: Max available limit
          type: int
          returned: always
          sample: 123
        is_boolean:
          description: Is boolean
          type: bool
          returned: always
          sample: true
        default_limit:
          description: Default limit
          type: int
          returned: always
          sample: 123
        factor:
          description: Factor
          type: int
          returned: always
          sample: 123
        is_builtin:
          description: Is builtin
          type: bool
          returned: always
          sample: true
        is_prepaid:
          description: Is prepaid
          type: bool
          returned: always
          sample: true
        overage_component:
          description: Overage component
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        min_prepaid_duration:
          description: Min prepaid duration
          type: int
          returned: always
          sample: 123
        max_prepaid_duration:
          description: Max prepaid duration
          type: int
          returned: always
          sample: 123
    plugin_options:
      description: Plugin options
      type: str
      returned: always
      sample: null
    state:
      description: State
      type: str
      returned: always
      sample: OK
    vendor_details:
      description: Vendor details
      type: str
      returned: always
      sample: string-value
    getting_started:
      description: Getting started
      type: str
      returned: always
      sample: string-value
    integration_guide:
      description: Integration guide
      type: str
      returned: always
      sample: string-value
    thumbnail:
      description: Thumbnail URL
      type: str
      returned: always
      sample: https://api.example.com/api/thumbnail/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    order_count:
      description: Order count
      type: int
      returned: always
      sample: 123
    plans:
      description: A list of plans items.
      type: list
      returned: always
      sample: []
      contains:
        url:
          description: URL URL
          type: str
          returned: always
          sample: https://api.example.com/api/url/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        uuid:
          description: UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        name:
          description: Name
          type: str
          returned: always
          sample: My-Awesome-offering
        description:
          description: Description
          type: str
          returned: always
          sample: A sample description created by Ansible.
        article_code:
          description: Article code
          type: str
          returned: always
          sample: string-value
        max_amount:
          description: Maximum number of plans that could be active. Plan is disabled when maximum amount is reached.
          type: int
          returned: always
          sample: 123
        archived:
          description: Forbids creation of new resources.
          type: bool
          returned: always
          sample: true
        is_active:
          description: Is active
          type: bool
          returned: always
          sample: true
        unit_price:
          description: Unit price
          type: str
          returned: always
          sample: '12.34'
        unit:
          description: Unit
          type: str
          returned: always
          sample: month
        init_price:
          description: Init price
          type: float
          returned: always
          sample: 123.45
        switch_price:
          description: Switch price
          type: float
          returned: always
          sample: 123.45
        backend_id:
          description: Backend ID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        organization_groups:
          description: A list of organization groups items.
          type: list
          returned: always
          sample: []
          contains:
            uuid:
              description: UUID
              type: str
              returned: always
              sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
            url:
              description: URL URL
              type: str
              returned: always
              sample: https://api.example.com/api/url/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
            name:
              description: Name
              type: str
              returned: always
              sample: My-Awesome-offering
            parent_uuid:
              description: Parent UUID
              type: str
              returned: always
              sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
            parent_name:
              description: Parent name
              type: str
              returned: always
              sample: string-value
            parent:
              description: Parent URL
              type: str
              returned: always
              sample: https://api.example.com/api/parent/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
            customers_count:
              description: Customers count
              type: int
              returned: always
              sample: 123
        components:
          description: A list of components items.
          type: list
          returned: always
          sample: []
          contains:
            type:
              description: Unique internal name of the measured unit, for example floating_ip.
              type: str
              returned: always
              sample: string-value
            name:
              description: Display name for the measured unit, for example, Floating IP.
              type: str
              returned: always
              sample: My-Awesome-offering
            measured_unit:
              description: Unit of measurement, for example, GB.
              type: str
              returned: always
              sample: string-value
            amount:
              description: Amount
              type: int
              returned: always
              sample: 123
            price:
              description: Price
              type: str
              returned: always
              sample: '12.34'
            future_price:
              description: Future price
              type: str
              returned: always
              sample: '12.34'
            discount_threshold:
              description: Minimum amount to be eligible for discount.
              type: int
              returned: always
              sample: 123
            discount_rate:
              description: Discount rate in percentage.
              type: int
              returned: always
              sample: 123
        prices:
          description: Prices
          type: dict
          returned: always
          sample: {}
        future_prices:
          description: Future prices
          type: dict
          returned: always
          sample: {}
        quotas:
          description: Quotas
          type: dict
          returned: always
          sample: {}
        resources_count:
          description: Resources count
          type: int
          returned: always
          sample: 123
        plan_type:
          description: Plan type
          type: str
          returned: always
          sample: string-value
        minimal_price:
          description: Minimal price
          type: float
          returned: always
          sample: 123.45
    screenshots:
      description: A list of screenshots items.
      type: list
      returned: always
      sample: []
      contains:
        name:
          description: Name
          type: str
          returned: always
          sample: My-Awesome-offering
        uuid:
          description: UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        description:
          description: Description
          type: str
          returned: always
          sample: A sample description created by Ansible.
        image:
          description: Image URL
          type: str
          returned: always
          sample: https://api.example.com/api/image/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        thumbnail:
          description: Thumbnail URL
          type: str
          returned: always
          sample: https://api.example.com/api/thumbnail/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        created:
          description: Created
          type: str
          returned: always
          sample: '2023-10-01T12:00:00Z'
    type:
      description: Type
      type: str
      returned: always
      sample: string-value
    shared:
      description: Accessible to all customers.
      type: bool
      returned: always
      sample: true
    billable:
      description: Purchase and usage is invoiced.
      type: bool
      returned: always
      sample: true
    scope:
      description: Scope
      type: str
      returned: always
      sample: string-value
    scope_uuid:
      description: Scope UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    scope_name:
      description: Scope name
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    scope_state:
      description: Scope state
      type: str
      returned: always
      sample: null
    scope_error_message:
      description: Scope error message
      type: str
      returned: always
      sample: string-value
    files:
      description: A list of files items.
      type: list
      returned: always
      sample: []
      contains:
        name:
          description: Name
          type: str
          returned: always
          sample: My-Awesome-offering
        created:
          description: Created
          type: str
          returned: always
          sample: '2023-10-01T12:00:00Z'
        file:
          description: File URL
          type: str
          returned: always
          sample: https://api.example.com/api/file/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    quotas:
      description: A list of quotas items.
      type: list
      returned: always
      sample: []
      contains:
        name:
          description: Name
          type: str
          returned: always
          sample: My-Awesome-offering
        usage:
          description: Usage
          type: int
          returned: always
          sample: 123
        limit:
          description: Limit
          type: int
          returned: always
          sample: 123
    paused_reason:
      description: Paused reason
      type: str
      returned: always
      sample: string-value
    datacite_doi:
      description: Datacite doi
      type: str
      returned: always
      sample: string-value
    citation_count:
      description: Number of citations of a DOI
      type: int
      returned: always
      sample: 123
    latitude:
      description: Latitude
      type: float
      returned: always
      sample: 123.45
    longitude:
      description: Longitude
      type: float
      returned: always
      sample: 123.45
    country:
      description: Country
      type: str
      returned: always
      sample: null
    backend_id:
      description: Backend ID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    organization_groups:
      description: A list of organization groups items.
      type: list
      returned: always
      sample: []
      contains:
        uuid:
          description: UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        url:
          description: URL URL
          type: str
          returned: always
          sample: https://api.example.com/api/url/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        name:
          description: Name
          type: str
          returned: always
          sample: My-Awesome-offering
        parent_uuid:
          description: Parent UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        parent_name:
          description: Parent name
          type: str
          returned: always
          sample: string-value
        parent:
          description: Parent URL
          type: str
          returned: always
          sample: https://api.example.com/api/parent/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        customers_count:
          description: Customers count
          type: int
          returned: always
          sample: 123
    image:
      description: Image URL
      type: str
      returned: always
      sample: https://api.example.com/api/image/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    total_customers:
      description: Total customers
      type: int
      returned: always
      sample: 123
    total_cost:
      description: Total cost
      type: int
      returned: always
      sample: 123
    total_cost_estimated:
      description: Total cost estimated
      type: int
      returned: always
      sample: 123
    parent_description:
      description: Parent description
      type: str
      returned: always
      sample: string-value
    parent_uuid:
      description: Parent UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    parent_name:
      description: Parent name
      type: str
      returned: always
      sample: string-value
    backend_metadata:
      description: Backend metadata
      type: str
      returned: always
      sample: null
    has_compliance_requirements:
      description: Has compliance requirements
      type: bool
      returned: always
      sample: true
    billing_type_classification:
      description: 'Classify offering components by billing type.

        Returns ''limit_only'', ''usage_only'', or ''mixed''.'
      type: str
      returned: always
      sample: string-value
    compliance_checklist:
      description: Compliance checklist URL
      type: str
      returned: always
      sample: https://api.example.com/api/compliance-checklist/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    user_has_consent:
      description: User has consent
      type: bool
      returned: always
      sample: true
    google_calendar_is_public:
      description: Google calendar is public
      type: bool
      returned: always
      sample: true
    google_calendar_link:
      description: Get the Google Calendar link for an offering.
      type: str
      returned: always
      sample: string-value
    promotion_campaigns:
      description: A list of promotion campaigns items.
      type: list
      returned: always
      sample: []
      contains:
        uuid:
          description: UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        name:
          description: Name
          type: str
          returned: always
          sample: My-Awesome-offering
        start_date:
          description: Starting from this date, the campaign is active.
          type: str
          returned: always
          sample: '2023-10-01'
        end_date:
          description: The last day the campaign is active.
          type: str
          returned: always
          sample: '2023-10-01'
        discount_type:
          description: Discount type
          type: str
          returned: always
          sample: discount
        discount:
          description: Discount
          type: int
          returned: always
          sample: 123
        stock:
          description: Stock
          type: int
          returned: always
          sample: 123
        description:
          description: Description
          type: str
          returned: always
          sample: A sample description created by Ansible.
        months:
          description: How many months in a row should the related service (when activated) get special deal (0 for indefinitely until active)
          type: int
          returned: always
          sample: 123
        service_provider:
          description: Service provider URL
          type: str
          returned: always
          sample: https://api.example.com/api/service-provider/a1b2c3d4-e5f6-7890-abcd-ef1234567890/

"""

ARGUMENT_SPEC = {
    "access_token": {"type": "str", "no_log": True, "required": True},
    "api_url": {"type": "str", "required": True},
    "name": {"type": "str", "required": True},
    "customer": {"type": "str"},
    "accessible_via_calls": {"type": "bool"},
    "allowed_customer_uuid": {"type": "str"},
    "attributes": {"type": "str"},
    "billable": {"type": "bool"},
    "can_create_offering_user": {"type": "bool"},
    "category_group_uuid": {"type": "str"},
    "category_uuid": {"type": "str"},
    "created": {"type": "str"},
    "description": {"type": "str"},
    "has_active_terms_of_service": {"type": "bool"},
    "has_terms_of_service": {"type": "bool"},
    "keyword": {"type": "str"},
    "modified": {"type": "str"},
    "organization_group_uuid": {"type": "list"},
    "parent_uuid": {"type": "str"},
    "project_uuid": {"type": "str"},
    "query": {"type": "str"},
    "resource_customer_uuid": {"type": "str"},
    "resource_project_uuid": {"type": "str"},
    "scope_uuid": {"type": "str"},
    "service_manager_uuid": {"type": "str"},
    "shared": {"type": "bool"},
    "state": {"type": "list", "choices": ["Active", "Archived", "Draft", "Paused"]},
    "type": {"type": "list"},
    "user_has_consent": {"type": "bool"},
    "user_has_offering_user": {"type": "bool"},
    "uuid_list": {"type": "str"},
}

RUNNER_CONTEXT = {
    "resource_type": "offering",
    "list_url": "/api/marketplace-public-offerings/",
    "retrieve_url": "/api/marketplace-public-offerings/{uuid}/",
    "identifier_param": "name",
    "resolvers": {
        "customer": {
            "url": "/api/customers/",
            "error_message": "Customer '{value}' not found.",
            "filter_key": "customer_uuid",
        }
    },
    "many": False,
    "inferred_filter_params": [
        "accessible_via_calls",
        "allowed_customer_uuid",
        "attributes",
        "billable",
        "can_create_offering_user",
        "category_group_uuid",
        "category_uuid",
        "created",
        "customer",
        "description",
        "has_active_terms_of_service",
        "has_terms_of_service",
        "keyword",
        "modified",
        "organization_group_uuid",
        "parent_uuid",
        "project_uuid",
        "query",
        "resource_customer_uuid",
        "resource_project_uuid",
        "scope_uuid",
        "service_manager_uuid",
        "shared",
        "state",
        "type",
        "user_has_consent",
        "user_has_offering_user",
        "uuid_list",
    ],
}


def main():
    """Main execution entrypoint for the Ansible module."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )
    runner = FactsRunner(module, RUNNER_CONTEXT)
    runner.run()


if __name__ == "__main__":
    main()
