#!/usr/bin/python
#
# THIS FILE IS AUTOGENERATED BY THE ANSIBLE MODULE GENERATOR - DO NOT EDIT
#
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.waldur.marketplace.plugins.module_utils.waldur.facts_runner import (
    FactsRunner,
)

ANSIBLE_METADATA = {
    "metadata_version": "1.1",
    "status": ["preview"],
    "supported_by": "OpenNode",
}

DOCUMENTATION = """
---
module: order_facts
short_description: Get facts about a specific order
description: ''
author: Waldur Team
options:
  access_token:
    description: An access token.
    required: true
    type: str
    no_log: true
  api_url:
    description: Fully qualified URL to the API.
    required: true
    type: str
  name:
    description: The name or UUID of the order.
    type: str
    required: true
requirements:
- python >= 3.11

"""

EXAMPLES = """
- name: Retrieve and print facts about orders
  hosts: localhost
  tasks:
  - name: Get facts about a specific order
    waldur.marketplace.order_facts:
      name: My Resource Name
      access_token: b83557fd8e2066e98f27dee8f3b3433cdc4183ce
      api_url: https://waldur.example.com
    register: resource_info
  - name: Print the retrieved resource facts
    ansible.builtin.debug:
      var: resource_info.orders

"""

RETURN = """
resource:
  description: A list of dictionaries, where each dictionary represents a order.
  type: list
  returned: always
  elements: dict
  contains:
    offering:
      description: Offering URL
      type: str
      returned: always
      sample: https://api.example.com/api/offering/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    offering_name:
      description: Offering name
      type: str
      returned: always
      sample: string-value
    offering_uuid:
      description: Offering UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    offering_description:
      description: Offering description
      type: str
      returned: always
      sample: string-value
    offering_image:
      description: Offering image URL
      type: str
      returned: always
      sample: https://api.example.com/api/offering-image/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    offering_thumbnail:
      description: Offering thumbnail URL
      type: str
      returned: always
      sample: https://api.example.com/api/offering-thumbnail/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    offering_type:
      description: Offering type
      type: str
      returned: always
      sample: string-value
    offering_shared:
      description: Accessible to all customers.
      type: bool
      returned: always
      sample: true
    offering_billable:
      description: Purchase and usage is invoiced.
      type: bool
      returned: always
      sample: true
    offering_plugin_options:
      description: Public data used by specific plugin, such as storage mode for OpenStack.
      type: str
      returned: always
      sample: null
    provider_name:
      description: Provider name
      type: str
      returned: always
      sample: string-value
    provider_uuid:
      description: Provider UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    category_title:
      description: Category title
      type: str
      returned: always
      sample: string-value
    category_uuid:
      description: Category UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    category_icon:
      description: Category icon URL
      type: str
      returned: always
      sample: https://api.example.com/api/category-icon/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    plan:
      description: Plan URL
      type: str
      returned: always
      sample: https://api.example.com/api/plan/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    plan_unit:
      description: Plan unit
      type: str
      returned: always
      sample: null
    plan_name:
      description: Plan name
      type: str
      returned: always
      sample: string-value
    plan_uuid:
      description: Plan UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    plan_description:
      description: Plan description
      type: str
      returned: always
      sample: string-value
    attributes:
      description: Attributes
      type: str
      returned: always
      sample: null
    limits:
      description: Limits
      type: dict
      returned: always
      sample: {}
    uuid:
      description: UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    created:
      description: Created
      type: str
      returned: always
      sample: '2023-10-01T12:00:00Z'
    modified:
      description: Modified
      type: str
      returned: always
      sample: '2023-10-01T12:00:00Z'
    type:
      description: Type
      type: str
      returned: always
      sample: null
    resource_uuid:
      description: Resource UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    resource_type:
      description: Resource type
      type: str
      returned: always
      sample: string-value
    resource_name:
      description: Resource name
      type: str
      returned: always
      sample: string-value
    cost:
      description: Cost
      type: str
      returned: always
      sample: '12.34'
    state:
      description: State
      type: str
      returned: always
      sample: OK
    output:
      description: Output
      type: str
      returned: always
      sample: string-value
    marketplace_resource_uuid:
      description: Marketplace resource UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    error_message:
      description: Error message
      type: str
      returned: always
      sample: string-value
    callback_url:
      description: Callback URL URL
      type: str
      returned: always
      sample: https://api.example.com/api/callback-url/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    completed_at:
      description: Completed at
      type: str
      returned: always
      sample: '2023-10-01T12:00:00Z'
    consumer_reviewed_by:
      description: Required. 128 characters or fewer. Lowercase letters, numbers and @/./+/-/_ characters
      type: str
      returned: always
      sample: https://api.example.com/api/users/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    consumer_reviewed_by_full_name:
      description: Consumer reviewed by full name
      type: str
      returned: always
      sample: string-value
    consumer_reviewed_by_username:
      description: Required. 128 characters or fewer. Lowercase letters, numbers and @/./+/-/_ characters
      type: str
      returned: always
      sample: string-value
    consumer_reviewed_at:
      description: Consumer reviewed at
      type: str
      returned: always
      sample: '2023-10-01T12:00:00Z'
    provider_reviewed_by:
      description: Required. 128 characters or fewer. Lowercase letters, numbers and @/./+/-/_ characters
      type: str
      returned: always
      sample: https://api.example.com/api/users/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    provider_reviewed_by_full_name:
      description: Provider reviewed by full name
      type: str
      returned: always
      sample: string-value
    provider_reviewed_by_username:
      description: Required. 128 characters or fewer. Lowercase letters, numbers and @/./+/-/_ characters
      type: str
      returned: always
      sample: string-value
    provider_reviewed_at:
      description: Provider reviewed at
      type: str
      returned: always
      sample: '2023-10-01T12:00:00Z'
    created_by_username:
      description: Required. 128 characters or fewer. Lowercase letters, numbers and @/./+/-/_ characters
      type: str
      returned: always
      sample: string-value
    created_by_full_name:
      description: Created by full name
      type: str
      returned: always
      sample: string-value
    created_by_civil_number:
      description: Created by civil number
      type: str
      returned: always
      sample: string-value
    customer_name:
      description: Customer name
      type: str
      returned: always
      sample: Big Corp Inc.
    customer_uuid:
      description: Customer UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    customer_slug:
      description: Customer slug
      type: str
      returned: always
      sample: string-value
    project_name:
      description: Project name
      type: str
      returned: always
      sample: Internal Research Project
    project_uuid:
      description: Project UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    project_description:
      description: Project description
      type: str
      returned: always
      sample: string-value
    project_slug:
      description: Project slug
      type: str
      returned: always
      sample: string-value
    old_plan_name:
      description: Old plan name
      type: str
      returned: always
      sample: string-value
    new_plan_name:
      description: New plan name
      type: str
      returned: always
      sample: string-value
    old_plan_uuid:
      description: Old plan UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    new_plan_uuid:
      description: New plan UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    old_cost_estimate:
      description: Old cost estimate
      type: str
      returned: always
      sample: '12.34'
    new_cost_estimate:
      description: New cost estimate
      type: str
      returned: always
      sample: '12.34'
    can_terminate:
      description: Can terminate
      type: bool
      returned: always
      sample: true
    fixed_price:
      description: Fixed price
      type: float
      returned: always
      sample: 123.45
    activation_price:
      description: Activation price
      type: float
      returned: always
      sample: 123.45
    termination_comment:
      description: Termination comment
      type: str
      returned: always
      sample: string-value
    backend_id:
      description: Backend ID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    issue:
      description: Issue
      type: str
      returned: always
      sample: null

"""

ARGUMENT_SPEC = {
    "access_token": {"type": "str", "no_log": True, "required": True},
    "api_url": {"type": "str", "required": True},
    "name": {"type": "str", "required": True},
}

RUNNER_CONTEXT = {
    "resource_type": "order",
    "list_url": "/api/marketplace-orders/",
    "retrieve_url": "/api/marketplace-orders/{uuid}/",
    "identifier_param": "name",
    "resolvers": {},
    "many": False,
}


def main():
    """Main execution entrypoint for the Ansible module."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )
    runner = FactsRunner(module, RUNNER_CONTEXT)
    runner.run()


if __name__ == "__main__":
    main()
