#!/usr/bin/python
#
# THIS FILE IS AUTOGENERATED BY THE ANSIBLE MODULE GENERATOR - DO NOT EDIT
#
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.waldur.marketplace.plugins.module_utils.waldur.actions_runner import (
    ActionsRunner,
)

ANSIBLE_METADATA = {
    "metadata_version": "1.1",
    "status": ["preview"],
    "supported_by": "OpenNode",
}

DOCUMENTATION = """
---
module: resource_action
short_description: Perform actions on a marketplace resource.
description: ''
author: Waldur Team
options:
  access_token:
    description: An access token.
    required: true
    type: str
    no_log: true
  api_url:
    description: Fully qualified URL to the API.
    required: true
    type: str
  name:
    description: The name or UUID of the marketplace resource to perform an action on.
    type: str
    required: true
  action:
    description: The action to perform on the resource.
    type: str
    required: true
    choices:
    - pull
    - terminate
    - unlink
  customer:
    description: The name or UUID of the parent customer for filtering.
    type: str
    required: false
  project:
    description: The name or UUID of the parent project for filtering.
    type: str
    required: false
requirements:
- python >= 3.9

"""

EXAMPLES = """
- name: Perform 'pull' action on a marketplace resource
  hosts: localhost
  tasks:
  - name: Trigger pull
    waldur.marketplace.resource_action:
      name: My-Target-marketplace-resource
      access_token: b83557fd8e2066e98f27dee8f3b3433cdc4183ce
      api_url: https://waldur.example.com
      customer: Parent Customer Name or UUID
      project: Parent Project Name or UUID
      action: pull
- name: Perform 'terminate' action on a marketplace resource
  hosts: localhost
  tasks:
  - name: Trigger terminate
    waldur.marketplace.resource_action:
      name: My-Target-marketplace-resource
      access_token: b83557fd8e2066e98f27dee8f3b3433cdc4183ce
      api_url: https://waldur.example.com
      customer: Parent Customer Name or UUID
      project: Parent Project Name or UUID
      action: terminate
- name: Perform 'unlink' action on a marketplace resource
  hosts: localhost
  tasks:
  - name: Trigger unlink
    waldur.marketplace.resource_action:
      name: My-Target-marketplace-resource
      access_token: b83557fd8e2066e98f27dee8f3b3433cdc4183ce
      api_url: https://waldur.example.com
      customer: Parent Customer Name or UUID
      project: Parent Project Name or UUID
      action: unlink

"""

RETURN = """
resource:
  description: A dictionary describing the marketplace resource after the action was performed.
  type: dict
  returned: on success
  contains:
    offering:
      description: Offering URL
      type: str
      returned: always
      sample: https://api.example.com/api/offering/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    offering_name:
      description: Offering name
      type: str
      returned: always
      sample: string-value
    offering_uuid:
      description: Offering UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    offering_description:
      description: Offering description
      type: str
      returned: always
      sample: string-value
    offering_image:
      description: Offering image URL
      type: str
      returned: always
      sample: https://api.example.com/api/offering-image/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    offering_thumbnail:
      description: Offering thumbnail URL
      type: str
      returned: always
      sample: https://api.example.com/api/offering-thumbnail/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    offering_type:
      description: Offering type
      type: str
      returned: always
      sample: string-value
    offering_shared:
      description: Accessible to all customers.
      type: bool
      returned: always
      sample: true
    offering_billable:
      description: Purchase and usage is invoiced.
      type: bool
      returned: always
      sample: true
    offering_plugin_options:
      description: Public data used by specific plugin, such as storage mode for OpenStack.
      type: str
      returned: always
      sample: null
    provider_name:
      description: Provider name
      type: str
      returned: always
      sample: string-value
    provider_uuid:
      description: Provider UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    provider_slug:
      description: Provider slug
      type: str
      returned: always
      sample: string-value
    category_title:
      description: Category title
      type: str
      returned: always
      sample: string-value
    category_uuid:
      description: Category UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    category_icon:
      description: Category icon URL
      type: str
      returned: always
      sample: https://api.example.com/api/category-icon/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    plan:
      description: Plan URL
      type: str
      returned: always
      sample: https://api.example.com/api/plan/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    plan_unit:
      description: Plan unit
      type: str
      returned: always
      sample: month
    plan_name:
      description: Plan name
      type: str
      returned: always
      sample: string-value
    plan_uuid:
      description: Plan UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    plan_description:
      description: Plan description
      type: str
      returned: always
      sample: string-value
    attributes:
      description: Attributes
      type: dict
      returned: always
      sample: {}
    limits:
      description: Limits
      type: dict
      returned: always
      sample: {}
    uuid:
      description: UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    created:
      description: Created
      type: str
      returned: always
      sample: '2023-10-01T12:00:00Z'
    modified:
      description: Modified
      type: str
      returned: always
      sample: '2023-10-01T12:00:00Z'
    url:
      description: URL URL
      type: str
      returned: always
      sample: https://api.example.com/api/url/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    scope:
      description: Scope
      type: str
      returned: always
      sample: string-value
    description:
      description: Description
      type: str
      returned: always
      sample: A sample description created by Ansible.
    state:
      description: State
      type: str
      returned: always
      sample: Creating
    resource_uuid:
      description: Resource UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    backend_id:
      description: Backend ID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    effective_id:
      description: Effective ID
      type: str
      returned: always
      sample: string-value
    resource_type:
      description: Resource type
      type: str
      returned: always
      sample: string-value
    project:
      description: Project URL
      type: str
      returned: always
      sample: https://api.example.com/api/project/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    project_uuid:
      description: Project UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    project_name:
      description: Project name
      type: str
      returned: always
      sample: Internal Research Project
    project_description:
      description: Project description
      type: str
      returned: always
      sample: string-value
    project_end_date:
      description: The date is inclusive. Once reached, all project resource will be scheduled for termination.
      type: str
      returned: always
      sample: '2023-10-01'
    project_end_date_requested_by:
      description: Project end date requested by URL
      type: str
      returned: always
      sample: https://api.example.com/api/users/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    customer_uuid:
      description: Customer UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    customer_name:
      description: Customer name
      type: str
      returned: always
      sample: Big Corp Inc.
    offering_slug:
      description: Offering slug
      type: str
      returned: always
      sample: string-value
    parent_offering_uuid:
      description: Parent offering UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    parent_offering_name:
      description: Parent offering name
      type: str
      returned: always
      sample: string-value
    parent_offering_slug:
      description: Parent offering slug
      type: str
      returned: always
      sample: string-value
    parent_uuid:
      description: Parent UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    parent_name:
      description: Parent name
      type: str
      returned: always
      sample: string-value
    backend_metadata:
      description: Backend metadata
      type: dict
      returned: always
      sample: {}
      contains:
        state:
          description: Backend resource state
          type: str
          returned: always
          sample: OK
        runtime_state:
          description: Runtime state of the backend resource
          type: str
          returned: always
          sample: string-value
        action:
          description: Current action being performed
          type: str
          returned: always
          sample: string-value
        instance_name:
          description: Name of the backend instance
          type: str
          returned: always
          sample: string-value
    is_usage_based:
      description: Is usage based
      type: bool
      returned: always
      sample: true
    is_limit_based:
      description: Is limit based
      type: bool
      returned: always
      sample: true
    name:
      description: Name
      type: str
      returned: always
      sample: My-Awesome-marketplace-resource
    slug:
      description: URL-friendly identifier. Only editable by staff users.
      type: str
      returned: always
      sample: string-value
    current_usages:
      description: Current usages
      type: dict
      returned: always
      sample: {}
    can_terminate:
      description: Can terminate
      type: bool
      returned: always
      sample: true
    report:
      description: A list of report items.
      type: list
      returned: always
      sample: []
      contains:
        header:
          description: Section header text
          type: str
          returned: always
          sample: string-value
        body:
          description: Section body content
          type: str
          returned: always
          sample: string-value
    end_date:
      description: The date is inclusive. Once reached, a resource will be scheduled for termination.
      type: str
      returned: always
      sample: '2023-10-01'
    end_date_requested_by:
      description: End date requested by URL
      type: str
      returned: always
      sample: https://api.example.com/api/users/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    username:
      description: Username
      type: str
      returned: always
      sample: alice
    limit_usage:
      description: Limit usage
      type: dict
      returned: always
      sample: {}
    downscaled:
      description: Downscaled
      type: bool
      returned: always
      sample: true
    restrict_member_access:
      description: Restrict member access
      type: bool
      returned: always
      sample: true
    paused:
      description: Paused
      type: bool
      returned: always
      sample: true
    endpoints:
      description: A list of endpoints items.
      type: list
      returned: always
      sample: []
      contains:
        uuid:
          description: UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        name:
          description: Name
          type: str
          returned: always
          sample: My-Awesome-marketplace-resource
        url:
          description: URL of the access endpoint
          type: str
          returned: always
          sample: string-value
    error_message:
      description: Error message
      type: str
      returned: always
      sample: string-value
    error_traceback:
      description: Error traceback
      type: str
      returned: always
      sample: string-value
    options:
      description: Options
      type: str
      returned: always
      sample: null
    available_actions:
      description: A list of available actions items.
      type: list
      returned: always
      sample: []
    last_sync:
      description: Last sync
      type: str
      returned: always
      sample: '2023-10-01T12:00:00Z'
    order_in_progress:
      description: Order in progress
      type: dict
      returned: always
      sample: {}
      contains:
        offering:
          description: Offering URL
          type: str
          returned: always
          sample: https://api.example.com/api/offering/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        offering_name:
          description: Offering name
          type: str
          returned: always
          sample: string-value
        offering_uuid:
          description: Offering UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        offering_description:
          description: Offering description
          type: str
          returned: always
          sample: string-value
        offering_image:
          description: Offering image URL
          type: str
          returned: always
          sample: https://api.example.com/api/offering-image/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        offering_thumbnail:
          description: Offering thumbnail URL
          type: str
          returned: always
          sample: https://api.example.com/api/offering-thumbnail/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        offering_type:
          description: Offering type
          type: str
          returned: always
          sample: string-value
        offering_shared:
          description: Accessible to all customers.
          type: bool
          returned: always
          sample: true
        offering_billable:
          description: Purchase and usage is invoiced.
          type: bool
          returned: always
          sample: true
        offering_plugin_options:
          description: Public data used by specific plugin, such as storage mode for OpenStack.
          type: str
          returned: always
          sample: null
        provider_name:
          description: Provider name
          type: str
          returned: always
          sample: string-value
        provider_uuid:
          description: Provider UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        provider_slug:
          description: Provider slug
          type: str
          returned: always
          sample: string-value
        category_title:
          description: Category title
          type: str
          returned: always
          sample: string-value
        category_uuid:
          description: Category UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        category_icon:
          description: Category icon URL
          type: str
          returned: always
          sample: https://api.example.com/api/category-icon/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        plan:
          description: Plan URL
          type: str
          returned: always
          sample: https://api.example.com/api/plan/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        plan_unit:
          description: Plan unit
          type: str
          returned: always
          sample: month
        plan_name:
          description: Plan name
          type: str
          returned: always
          sample: string-value
        plan_uuid:
          description: Plan UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        plan_description:
          description: Plan description
          type: str
          returned: always
          sample: string-value
        attributes:
          description: Attributes
          type: str
          returned: always
          sample: null
        limits:
          description: Limits
          type: dict
          returned: always
          sample: {}
        uuid:
          description: UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        created:
          description: Created
          type: str
          returned: always
          sample: '2023-10-01T12:00:00Z'
        modified:
          description: Modified
          type: str
          returned: always
          sample: '2023-10-01T12:00:00Z'
        resource_uuid:
          description: Resource UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        resource_type:
          description: Resource type
          type: str
          returned: always
          sample: string-value
        resource_name:
          description: Resource name
          type: str
          returned: always
          sample: string-value
        cost:
          description: Cost
          type: str
          returned: always
          sample: '12.34'
        state:
          description: State
          type: str
          returned: always
          sample: pending-start-date
        output:
          description: Output
          type: str
          returned: always
          sample: string-value
        marketplace_resource_uuid:
          description: Marketplace resource UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        error_message:
          description: Error message
          type: str
          returned: always
          sample: string-value
        error_traceback:
          description: Error traceback
          type: str
          returned: always
          sample: string-value
        callback_url:
          description: Callback URL URL
          type: str
          returned: always
          sample: https://api.example.com/api/callback-url/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        completed_at:
          description: Completed at
          type: str
          returned: always
          sample: '2023-10-01T12:00:00Z'
        request_comment:
          description: Request comment
          type: str
          returned: always
          sample: string-value
        attachment:
          description: Attachment URL
          type: str
          returned: always
          sample: https://api.example.com/api/attachment/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        type:
          description: Type
          type: str
          returned: always
          sample: Create
        start_date:
          description: Enables delayed processing of resource provisioning order.
          type: str
          returned: always
          sample: '2023-10-01'
        slug:
          description: Slug
          type: str
          returned: always
          sample: string-value
        url:
          description: URL URL
          type: str
          returned: always
          sample: https://api.example.com/api/url/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        consumer_reviewed_by:
          description: Required. 128 characters or fewer. Lowercase letters, numbers and @/./+/-/_ characters
          type: str
          returned: always
          sample: https://api.example.com/api/users/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        consumer_reviewed_by_full_name:
          description: Consumer reviewed by full name
          type: str
          returned: always
          sample: string-value
        consumer_reviewed_by_username:
          description: Required. 128 characters or fewer. Lowercase letters, numbers and @/./+/-/_ characters
          type: str
          returned: always
          sample: string-value
        consumer_reviewed_at:
          description: Consumer reviewed at
          type: str
          returned: always
          sample: '2023-10-01T12:00:00Z'
        provider_reviewed_by:
          description: Required. 128 characters or fewer. Lowercase letters, numbers and @/./+/-/_ characters
          type: str
          returned: always
          sample: https://api.example.com/api/users/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        provider_reviewed_by_full_name:
          description: Provider reviewed by full name
          type: str
          returned: always
          sample: string-value
        provider_reviewed_by_username:
          description: Required. 128 characters or fewer. Lowercase letters, numbers and @/./+/-/_ characters
          type: str
          returned: always
          sample: string-value
        provider_reviewed_at:
          description: Provider reviewed at
          type: str
          returned: always
          sample: '2023-10-01T12:00:00Z'
        created_by_username:
          description: Required. 128 characters or fewer. Lowercase letters, numbers and @/./+/-/_ characters
          type: str
          returned: always
          sample: string-value
        created_by_full_name:
          description: Created by full name
          type: str
          returned: always
          sample: string-value
        created_by_civil_number:
          description: Created by civil number
          type: str
          returned: always
          sample: string-value
        customer_name:
          description: Customer name
          type: str
          returned: always
          sample: Big Corp Inc.
        customer_uuid:
          description: Customer UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        customer_slug:
          description: Customer slug
          type: str
          returned: always
          sample: string-value
        project_name:
          description: Project name
          type: str
          returned: always
          sample: Internal Research Project
        project_uuid:
          description: Project UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        project_description:
          description: Project description
          type: str
          returned: always
          sample: string-value
        project_slug:
          description: Project slug
          type: str
          returned: always
          sample: string-value
        old_plan_name:
          description: Old plan name
          type: str
          returned: always
          sample: string-value
        new_plan_name:
          description: New plan name
          type: str
          returned: always
          sample: string-value
        old_plan_uuid:
          description: Old plan UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        new_plan_uuid:
          description: New plan UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        old_cost_estimate:
          description: Old cost estimate
          type: float
          returned: always
          sample: 123.45
        new_cost_estimate:
          description: New cost estimate
          type: str
          returned: always
          sample: '12.34'
        can_terminate:
          description: Can terminate
          type: bool
          returned: always
          sample: true
        fixed_price:
          description: Fixed price
          type: float
          returned: always
          sample: 123.45
        activation_price:
          description: Activation price
          type: float
          returned: always
          sample: 123.45
        termination_comment:
          description: Termination comment
          type: str
          returned: always
          sample: string-value
        backend_id:
          description: Backend ID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        order_subtype:
          description: Order subtype
          type: str
          returned: always
          sample: string-value
        issue:
          description: Issue
          type: dict
          returned: always
          sample: {}
          contains:
            key:
              description: Key
              type: str
              returned: always
              sample: special-key
            uuid:
              description: UUID
              type: str
              returned: always
              sample: string-value
    creation_order:
      description: Creation order
      type: dict
      returned: always
      sample: {}
      contains:
        offering:
          description: Offering URL
          type: str
          returned: always
          sample: https://api.example.com/api/offering/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        offering_name:
          description: Offering name
          type: str
          returned: always
          sample: string-value
        offering_uuid:
          description: Offering UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        offering_description:
          description: Offering description
          type: str
          returned: always
          sample: string-value
        offering_image:
          description: Offering image URL
          type: str
          returned: always
          sample: https://api.example.com/api/offering-image/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        offering_thumbnail:
          description: Offering thumbnail URL
          type: str
          returned: always
          sample: https://api.example.com/api/offering-thumbnail/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        offering_type:
          description: Offering type
          type: str
          returned: always
          sample: string-value
        offering_shared:
          description: Accessible to all customers.
          type: bool
          returned: always
          sample: true
        offering_billable:
          description: Purchase and usage is invoiced.
          type: bool
          returned: always
          sample: true
        offering_plugin_options:
          description: Public data used by specific plugin, such as storage mode for OpenStack.
          type: str
          returned: always
          sample: null
        provider_name:
          description: Provider name
          type: str
          returned: always
          sample: string-value
        provider_uuid:
          description: Provider UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        provider_slug:
          description: Provider slug
          type: str
          returned: always
          sample: string-value
        category_title:
          description: Category title
          type: str
          returned: always
          sample: string-value
        category_uuid:
          description: Category UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        category_icon:
          description: Category icon URL
          type: str
          returned: always
          sample: https://api.example.com/api/category-icon/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        plan:
          description: Plan URL
          type: str
          returned: always
          sample: https://api.example.com/api/plan/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        plan_unit:
          description: Plan unit
          type: str
          returned: always
          sample: month
        plan_name:
          description: Plan name
          type: str
          returned: always
          sample: string-value
        plan_uuid:
          description: Plan UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        plan_description:
          description: Plan description
          type: str
          returned: always
          sample: string-value
        attributes:
          description: Attributes
          type: str
          returned: always
          sample: null
        limits:
          description: Limits
          type: dict
          returned: always
          sample: {}
        uuid:
          description: UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        created:
          description: Created
          type: str
          returned: always
          sample: '2023-10-01T12:00:00Z'
        modified:
          description: Modified
          type: str
          returned: always
          sample: '2023-10-01T12:00:00Z'
        resource_uuid:
          description: Resource UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        resource_type:
          description: Resource type
          type: str
          returned: always
          sample: string-value
        resource_name:
          description: Resource name
          type: str
          returned: always
          sample: string-value
        cost:
          description: Cost
          type: str
          returned: always
          sample: '12.34'
        state:
          description: State
          type: str
          returned: always
          sample: pending-start-date
        output:
          description: Output
          type: str
          returned: always
          sample: string-value
        marketplace_resource_uuid:
          description: Marketplace resource UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        error_message:
          description: Error message
          type: str
          returned: always
          sample: string-value
        error_traceback:
          description: Error traceback
          type: str
          returned: always
          sample: string-value
        callback_url:
          description: Callback URL URL
          type: str
          returned: always
          sample: https://api.example.com/api/callback-url/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        completed_at:
          description: Completed at
          type: str
          returned: always
          sample: '2023-10-01T12:00:00Z'
        request_comment:
          description: Request comment
          type: str
          returned: always
          sample: string-value
        attachment:
          description: Attachment URL
          type: str
          returned: always
          sample: https://api.example.com/api/attachment/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        type:
          description: Type
          type: str
          returned: always
          sample: Create
        start_date:
          description: Enables delayed processing of resource provisioning order.
          type: str
          returned: always
          sample: '2023-10-01'
        slug:
          description: Slug
          type: str
          returned: always
          sample: string-value
        url:
          description: URL URL
          type: str
          returned: always
          sample: https://api.example.com/api/url/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        consumer_reviewed_by:
          description: Required. 128 characters or fewer. Lowercase letters, numbers and @/./+/-/_ characters
          type: str
          returned: always
          sample: https://api.example.com/api/users/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        consumer_reviewed_by_full_name:
          description: Consumer reviewed by full name
          type: str
          returned: always
          sample: string-value
        consumer_reviewed_by_username:
          description: Required. 128 characters or fewer. Lowercase letters, numbers and @/./+/-/_ characters
          type: str
          returned: always
          sample: string-value
        consumer_reviewed_at:
          description: Consumer reviewed at
          type: str
          returned: always
          sample: '2023-10-01T12:00:00Z'
        provider_reviewed_by:
          description: Required. 128 characters or fewer. Lowercase letters, numbers and @/./+/-/_ characters
          type: str
          returned: always
          sample: https://api.example.com/api/users/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        provider_reviewed_by_full_name:
          description: Provider reviewed by full name
          type: str
          returned: always
          sample: string-value
        provider_reviewed_by_username:
          description: Required. 128 characters or fewer. Lowercase letters, numbers and @/./+/-/_ characters
          type: str
          returned: always
          sample: string-value
        provider_reviewed_at:
          description: Provider reviewed at
          type: str
          returned: always
          sample: '2023-10-01T12:00:00Z'
        created_by_username:
          description: Required. 128 characters or fewer. Lowercase letters, numbers and @/./+/-/_ characters
          type: str
          returned: always
          sample: string-value
        created_by_full_name:
          description: Created by full name
          type: str
          returned: always
          sample: string-value
        created_by_civil_number:
          description: Created by civil number
          type: str
          returned: always
          sample: string-value
        customer_name:
          description: Customer name
          type: str
          returned: always
          sample: Big Corp Inc.
        customer_uuid:
          description: Customer UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        customer_slug:
          description: Customer slug
          type: str
          returned: always
          sample: string-value
        project_name:
          description: Project name
          type: str
          returned: always
          sample: Internal Research Project
        project_uuid:
          description: Project UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        project_description:
          description: Project description
          type: str
          returned: always
          sample: string-value
        project_slug:
          description: Project slug
          type: str
          returned: always
          sample: string-value
        old_plan_name:
          description: Old plan name
          type: str
          returned: always
          sample: string-value
        new_plan_name:
          description: New plan name
          type: str
          returned: always
          sample: string-value
        old_plan_uuid:
          description: Old plan UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        new_plan_uuid:
          description: New plan UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        old_cost_estimate:
          description: Old cost estimate
          type: float
          returned: always
          sample: 123.45
        new_cost_estimate:
          description: New cost estimate
          type: str
          returned: always
          sample: '12.34'
        can_terminate:
          description: Can terminate
          type: bool
          returned: always
          sample: true
        fixed_price:
          description: Fixed price
          type: float
          returned: always
          sample: 123.45
        activation_price:
          description: Activation price
          type: float
          returned: always
          sample: 123.45
        termination_comment:
          description: Termination comment
          type: str
          returned: always
          sample: string-value
        backend_id:
          description: Backend ID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        order_subtype:
          description: Order subtype
          type: str
          returned: always
          sample: string-value
        issue:
          description: Issue
          type: dict
          returned: always
          sample: {}
          contains:
            key:
              description: Key
              type: str
              returned: always
              sample: special-key
            uuid:
              description: UUID
              type: str
              returned: always
              sample: string-value
    service_settings_uuid:
      description: Service settings UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    project_slug:
      description: Project slug
      type: str
      returned: always
      sample: string-value
    customer_slug:
      description: Customer slug
      type: str
      returned: always
      sample: string-value
    user_requires_reconsent:
      description: Check if the current user needs to re-consent for this resource's offering.
      type: bool
      returned: always
      sample: true
    renewal_date:
      description: Renewal date
      type: dict
      returned: always
      sample: {}
    offering_state:
      description: Offering state
      type: str
      returned: always
      sample: Draft
    offering_components:
      description: A list of offering components items.
      type: list
      returned: always
      sample: []
      contains:
        uuid:
          description: UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        billing_type:
          description: Billing type
          type: str
          returned: always
          sample: fixed
        type:
          description: Unique internal name of the measured unit, for example floating_ip.
          type: str
          returned: always
          sample: string-value
        name:
          description: Display name for the measured unit, for example, Floating IP.
          type: str
          returned: always
          sample: My-Awesome-marketplace-resource
        description:
          description: Description
          type: str
          returned: always
          sample: A sample description created by Ansible.
        measured_unit:
          description: Unit of measurement, for example, GB.
          type: str
          returned: always
          sample: string-value
        unit_factor:
          description: The conversion factor from backend units to measured_unit
          type: int
          returned: always
          sample: 123
        limit_period:
          description: Limit period
          type: str
          returned: always
          sample: null
        limit_amount:
          description: Limit amount
          type: int
          returned: always
          sample: 123
        article_code:
          description: Article code
          type: str
          returned: always
          sample: string-value
        max_value:
          description: Max value
          type: int
          returned: always
          sample: 123
        min_value:
          description: Min value
          type: int
          returned: always
          sample: 123
        max_available_limit:
          description: Max available limit
          type: int
          returned: always
          sample: 123
        is_boolean:
          description: Is boolean
          type: bool
          returned: always
          sample: true
        default_limit:
          description: Default limit
          type: int
          returned: always
          sample: 123
        factor:
          description: Factor
          type: int
          returned: always
          sample: 123
        is_builtin:
          description: Is builtin
          type: bool
          returned: always
          sample: true
        is_prepaid:
          description: Is prepaid
          type: bool
          returned: always
          sample: true
        overage_component:
          description: Overage component
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        min_prepaid_duration:
          description: Min prepaid duration
          type: int
          returned: always
          sample: 123
        max_prepaid_duration:
          description: Max prepaid duration
          type: int
          returned: always
          sample: 123
commands:
  description: A list of HTTP requests that were made (or would be made in check mode) to execute the task.
  type: list
  returned: when changed
  elements: dict
  contains:
    method:
      description: The HTTP method used (e.g., POST, PATCH, DELETE).
      type: str
      sample: POST
    url:
      description: The fully qualified URL of the API endpoint.
      type: str
      sample: https://api.example.com/api/projects/
    description:
      description: A human-readable summary of the command's purpose.
      type: str
      sample: Create new project
    body:
      description: The JSON payload sent with the request. Only present for methods with a body.
      type: dict
      returned: if applicable
      sample:
        name: My-Awesome-Project

"""

ARGUMENT_SPEC = {
    "access_token": {"type": "str", "no_log": True, "required": True},
    "api_url": {"type": "str", "required": True},
    "name": {"type": "str", "required": True},
    "action": {
        "type": "str",
        "choices": ["pull", "terminate", "unlink"],
        "required": True,
    },
    "customer": {"type": "str"},
    "project": {"type": "str"},
}

RUNNER_CONTEXT = {
    "resource_type": "marketplace resource",
    "check_url": "/api/marketplace-resources/",
    "check_filter_keys": {"customer": "customer_uuid", "project": "project_uuid"},
    "retrieve_url": "/api/marketplace-resources/{uuid}/",
    "identifier_param": "name",
    "resolvers": {
        "customer": {
            "url": "/api/customers/",
            "error_message": "Customer '{value}' not found.",
        },
        "project": {
            "url": "/api/projects/",
            "error_message": "Project '{value}' not found.",
        },
    },
    "actions": {
        "pull": "/api/marketplace-resources/{uuid}/pull/",
        "terminate": "/api/marketplace-resources/{uuid}/terminate/",
        "unlink": "/api/marketplace-resources/{uuid}/unlink/",
    },
}


def main():
    """Main execution entrypoint for the Ansible module."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )
    runner = ActionsRunner(module, RUNNER_CONTEXT)
    runner.run()


if __name__ == "__main__":
    main()
