namespace: waldur
name: openstack
version: 7.9.5-dev.20251219085641
readme: README.md
authors:
- Waldur Team <info@waldur.com>
description: A collection of Ansible modules for managing Waldur resources, generated
  automatically.
license:
- MIT
tags:
- waldur
- cloud
- management
- automation
dependencies: {}
repository: https://github.com/waldur/ansible-waldur-module-next
documentation: https://docs.waldur.com/
homepage: https://waldur.com/
issues: https://github.com/waldur/ansible-waldur-module-next/issues
