#!/usr/bin/python
#
# THIS FILE IS AUTOGENERATED BY THE ANSIBLE MODULE GENERATOR - DO NOT EDIT
#
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.waldur.openstack.plugins.module_utils.waldur.crud_runner import (
    CrudRunner,
)

ANSIBLE_METADATA = {
    "metadata_version": "1.1",
    "status": ["preview"],
    "supported_by": "OpenNode",
}

DOCUMENTATION = """
---
module: network
short_description: Manage OpenStack Networks in Waldur.
description:
- Manage OpenStack Networks in Waldur.
author: Waldur Team
options:
  access_token:
    description: An access token.
    required: true
    type: str
    no_log: true
  api_url:
    description: Fully qualified URL to the API.
    required: true
    type: str
  state:
    description: Should the resource be present or absent.
    choices:
    - present
    - absent
    default: present
    type: str
  wait:
    description: A boolean value that defines whether to wait for the async action to complete.
    default: true
    type: bool
  timeout:
    description: The maximum number of seconds to wait for the async action to complete.
    default: 600
    type: int
  interval:
    description: The interval in seconds for polling the async action status.
    default: 20
    type: int
  name:
    type: str
    required: true
    description: The name of the network to check/create/delete.
  tenant:
    type: str
    required: true
    description: The parent tenant name or UUID for creating the resource.
  description:
    type: str
    required: false
    description: Description
  mtu:
    type: dict
    required: false
    description: ''
requirements:
- python >= 3.11

"""

EXAMPLES = """
- name: Create a new OpenStack network
  hosts: localhost
  tasks:
  - name: Add OpenStack network
    waldur.openstack.network:
      state: present
      access_token: b83557fd8e2066e98f27dee8f3b3433cdc4183ce
      api_url: https://waldur.example.com
      tenant: Tenant name or UUID
      name: My-Awesome-OpenStack-network
      description: A sample description created by Ansible.
- name: Remove an existing OpenStack network
  hosts: localhost
  tasks:
  - name: Remove OpenStack network
    waldur.openstack.network:
      state: absent
      name: My-Awesome-OpenStack-network
      access_token: b83557fd8e2066e98f27dee8f3b3433cdc4183ce
      api_url: https://waldur.example.com
      tenant: Tenant name or UUID

"""

RETURN = """
resource:
  description: The state of the OpenStack network after the operation.
  type: dict
  returned: on success
  contains:
    url:
      description: URL URL
      type: str
      returned: always
      sample: https://api.example.com/api/url/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    uuid:
      description: UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    name:
      description: Name
      type: str
      returned: always
      sample: My-Awesome-Resource
    description:
      description: Description
      type: str
      returned: always
      sample: A sample description created by Ansible.
    service_name:
      description: Service name
      type: str
      returned: always
      sample: string-value
    service_settings:
      description: Service settings URL
      type: str
      returned: always
      sample: https://api.example.com/api/service-settings/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    service_settings_uuid:
      description: Service settings UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    service_settings_state:
      description: Service settings state
      type: str
      returned: always
      sample: string-value
    service_settings_error_message:
      description: Service settings error message
      type: str
      returned: always
      sample: string-value
    project:
      description: Project URL
      type: str
      returned: always
      sample: https://api.example.com/api/project/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    project_name:
      description: Project name
      type: str
      returned: always
      sample: Internal Research Project
    project_uuid:
      description: Project UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    customer:
      description: Customer URL
      type: str
      returned: always
      sample: https://api.example.com/api/customer/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    customer_name:
      description: Customer name
      type: str
      returned: always
      sample: Big Corp Inc.
    customer_native_name:
      description: Customer native name
      type: str
      returned: always
      sample: string-value
    customer_abbreviation:
      description: Customer abbreviation
      type: str
      returned: always
      sample: string-value
    error_message:
      description: Error message
      type: str
      returned: always
      sample: string-value
    error_traceback:
      description: Error traceback
      type: str
      returned: always
      sample: string-value
    resource_type:
      description: Resource type
      type: str
      returned: always
      sample: string-value
    state:
      description: State
      type: str
      returned: always
      sample: OK
    created:
      description: Created
      type: str
      returned: always
      sample: '2023-10-01T12:00:00Z'
    modified:
      description: Modified
      type: str
      returned: always
      sample: '2023-10-01T12:00:00Z'
    backend_id:
      description: Backend ID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    access_url:
      description: Access URL
      type: str
      returned: always
      sample: string-value
    tenant:
      description: OpenStack tenant this network belongs to
      type: str
      returned: always
      sample: https://api.example.com/api/tenant/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    tenant_name:
      description: Tenant name
      type: str
      returned: always
      sample: string-value
    tenant_uuid:
      description: Tenant UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    is_external:
      description: Defines whether this network is external (public) or internal (private)
      type: bool
      returned: always
      sample: true
    type:
      description: Network type, such as local, flat, vlan, vxlan, or gre
      type: str
      returned: always
      sample: string-value
    subnets:
      description: A list of subnets items.
      type: list
      returned: always
      sample: []
      contains:
        uuid:
          description: UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        name:
          description: Name
          type: str
          returned: always
          sample: My-Awesome-Resource
        description:
          description: Description
          type: str
          returned: always
          sample: A sample description created by Ansible.
        cidr:
          description: IPv4 network address in CIDR format (e.g. 192.168.0.0/24)
          type: str
          returned: always
          sample: 192.168.1.0/24
        gateway_ip:
          description: IP address of the gateway for this subnet
          type: str
          returned: always
          sample: 192.168.1.1
        allocation_pools:
          description: A list of allocation pools items.
          type: list
          returned: always
          sample: []
          contains:
            start:
              description: Start
              type: str
              returned: always
              sample: string-value
            end:
              description: End
              type: str
              returned: always
              sample: string-value
        ip_version:
          description: IP protocol version (4 or 6)
          type: int
          returned: always
          sample: 123
        enable_dhcp:
          description: If True, DHCP service will be enabled on this subnet
          type: bool
          returned: always
          sample: true
    mtu:
      description: The maximum transmission unit (MTU) value to address fragmentation.
      type: int
      returned: always
      sample: 123
    rbac_policies:
      description: A list of rbac policies items.
      type: list
      returned: always
      sample: []
      contains:
        url:
          description: URL URL
          type: str
          returned: always
          sample: https://api.example.com/api/url/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        uuid:
          description: UUID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        network:
          description: Network URL
          type: str
          returned: always
          sample: https://api.example.com/api/network/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        network_name:
          description: Network name
          type: str
          returned: always
          sample: string-value
        target_tenant:
          description: Target tenant URL
          type: str
          returned: always
          sample: https://api.example.com/api/target-tenant/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
        target_tenant_name:
          description: Target tenant name
          type: str
          returned: always
          sample: string-value
        backend_id:
          description: Backend ID
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        policy_type:
          description: Type of access granted - either shared access or external network access
          type: str
          returned: always
          sample: null
        created:
          description: Created
          type: str
          returned: always
          sample: '2023-10-01T12:00:00Z'
    marketplace_offering_uuid:
      description: Marketplace offering UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    marketplace_offering_name:
      description: Marketplace offering name
      type: str
      returned: always
      sample: string-value
    marketplace_offering_plugin_options:
      description: Marketplace offering plugin options
      type: dict
      returned: always
      sample: {}
    marketplace_category_uuid:
      description: Marketplace category UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    marketplace_category_name:
      description: Marketplace category name
      type: str
      returned: always
      sample: string-value
    marketplace_resource_uuid:
      description: Marketplace resource UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    marketplace_plan_uuid:
      description: Marketplace plan UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    marketplace_resource_state:
      description: Marketplace resource state
      type: str
      returned: always
      sample: string-value
    is_usage_based:
      description: Is usage based
      type: bool
      returned: always
      sample: true
    is_limit_based:
      description: Is limit based
      type: bool
      returned: always
      sample: true

"""

ARGUMENT_SPEC = {
    "access_token": {"type": "str", "no_log": True, "required": True},
    "api_url": {"type": "str", "required": True},
    "state": {"type": "str", "choices": ["present", "absent"], "default": "present"},
    "wait": {"type": "bool", "default": True},
    "timeout": {"type": "int", "default": 600},
    "interval": {"type": "int", "default": 20},
    "name": {"type": "str", "required": True},
    "tenant": {"type": "str", "required": True},
    "description": {"type": "str"},
    "mtu": {"type": "dict"},
}

RUNNER_CONTEXT = {
    "resource_type": "OpenStack network",
    "check_url": "/api/openstack-networks/",
    "check_filter_keys": {},
    "list_path": "/api/openstack-networks/",
    "create_path": "/api/openstack-tenants/{uuid}/create_network/",
    "destroy_path": "/api/openstack-networks/{uuid}/",
    "update_path": "/api/openstack-networks/{uuid}/",
    "model_param_names": ["description", "name"],
    "path_param_maps": {"create": {"uuid": "tenant"}},
    "update_fields": ["description", "name"],
    "update_actions": {
        "set_mtu": {
            "path": "/api/openstack-networks/{uuid}/set_mtu/",
            "param": "mtu",
            "compare_key": "mtu",
            "wrap_in_object": True,
            "idempotency_keys": [],
            "defaults_map": {},
        }
    },
    "resolvers": {"tenant": {"url": "/api/openstack-tenants/", "error_message": None}},
    "resource_detail_path": "/api/openstack-networks/{uuid}/",
    "wait_config": {
        "ok_states": ["OK"],
        "erred_states": ["ERRED"],
        "state_field": "state",
    },
}


def main():
    """Main execution entrypoint for the Ansible module."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )
    runner = CrudRunner(module, RUNNER_CONTEXT)
    runner.run()


if __name__ == "__main__":
    main()
