#!/usr/bin/python
#
# THIS FILE IS AUTOGENERATED BY THE ANSIBLE MODULE GENERATOR - DO NOT EDIT
#
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.waldur.openstack.plugins.module_utils.waldur.order_runner import (
    OrderRunner,
)

ANSIBLE_METADATA = {
    "metadata_version": "1.1",
    "status": ["preview"],
    "supported_by": "OpenNode",
}

DOCUMENTATION = """
---
module: vpc
short_description: Create, update, or delete an OpenStack Tenant via the marketplace.
description:
- Create, update, or delete an OpenStack Tenant via the marketplace.
author: Waldur Team
options:
  access_token:
    description: An access token.
    required: true
    type: str
    no_log: true
  api_url:
    description: Fully qualified URL to the API.
    required: true
    type: str
  state:
    description: Should the resource be present or absent.
    choices:
    - present
    - absent
    default: present
    type: str
  wait:
    description: A boolean value that defines whether to wait for the order to complete.
    default: true
    type: bool
  timeout:
    description: The maximum number of seconds to wait for the order to complete.
    default: 600
    type: int
  interval:
    description: The interval in seconds for polling the order status.
    default: 20
    type: int
  name:
    type: str
    required: true
    description: Name
  project:
    type: str
    required: true
    description: The name or UUID of the project.
  offering:
    type: str
    required: true
    description: The name or UUID of the marketplace offering.
  plan:
    type: str
    required: false
    description: URL of the marketplace plan.
  limits:
    type: object
    required: false
    description: Marketplace resource limits for limit-based billing.
  description:
    type: str
    required: false
    description: Description
  subnet_cidr:
    type: str
    required: false
    description: Subnet CIDR
  skip_connection_extnet:
    type: bool
    required: false
    description: Skip connection extnet
  skip_creation_of_default_router:
    type: bool
    required: false
    description: Skip creation of default router
  availability_zone:
    type: str
    required: false
    description: Optional availability group. Will be used for all instances provisioned in this tenant
requirements:
- python >= 3.11

"""

EXAMPLES = """
- name: Create a new OpenStack tenant
  hosts: localhost
  tasks:
  - name: Add OpenStack tenant
    waldur.openstack.vpc:
      state: present
      access_token: b83557fd8e2066e98f27dee8f3b3433cdc4183ce
      api_url: https://waldur.example.com/api
      project: Project Name or UUID
      offering: Offering Name or UUID
      name: My-Awesome-OpenStack-tenant
      description: A sample description created by Ansible.
      subnet_cidr: 192.168.1.0/24
      skip_connection_extnet: true
      skip_creation_of_default_router: true
      availability_zone: string-value
- name: Remove an existing OpenStack tenant
  hosts: localhost
  tasks:
  - name: Remove OpenStack tenant
    waldur.openstack.vpc:
      state: absent
      name: My-Awesome-OpenStack-tenant
      access_token: b83557fd8e2066e98f27dee8f3b3433cdc4183ce
      api_url: https://waldur.example.com/api
      project: Project Name or UUID
      offering: Offering Name or UUID

"""

RETURN = """
resource:
  description: A dictionary describing the OpenStack tenant after a successful 'present' state.
  type: dict
  returned: on success when state is 'present'
  contains:
    url:
      description: URL URL
      type: str
      returned: always
      sample: https://api.example.com/api/url/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    uuid:
      description: UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    name:
      description: Name
      type: str
      returned: always
      sample: My-Awesome-Resource
    description:
      description: Description
      type: str
      returned: always
      sample: A sample description created by Ansible.
    service_name:
      description: Service name
      type: str
      returned: always
      sample: string-value
    service_settings:
      description: Service settings URL
      type: str
      returned: always
      sample: https://api.example.com/api/service-settings/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    service_settings_uuid:
      description: Service settings UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    service_settings_state:
      description: Service settings state
      type: str
      returned: always
      sample: string-value
    service_settings_error_message:
      description: Service settings error message
      type: str
      returned: always
      sample: string-value
    project:
      description: Project URL
      type: str
      returned: always
      sample: https://api.example.com/api/project/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    project_name:
      description: Project name
      type: str
      returned: always
      sample: Internal Research Project
    project_uuid:
      description: Project UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    customer:
      description: Customer URL
      type: str
      returned: always
      sample: https://api.example.com/api/customer/a1b2c3d4-e5f6-7890-abcd-ef1234567890/
    customer_name:
      description: Customer name
      type: str
      returned: always
      sample: Big Corp Inc.
    customer_native_name:
      description: Customer native name
      type: str
      returned: always
      sample: string-value
    customer_abbreviation:
      description: Customer abbreviation
      type: str
      returned: always
      sample: string-value
    error_message:
      description: Error message
      type: str
      returned: always
      sample: string-value
    error_traceback:
      description: Error traceback
      type: str
      returned: always
      sample: string-value
    resource_type:
      description: Resource type
      type: str
      returned: always
      sample: string-value
    state:
      description: State
      type: str
      returned: always
      sample: OK
    created:
      description: Created
      type: str
      returned: always
      sample: '2023-10-01T12:00:00Z'
    modified:
      description: Modified
      type: str
      returned: always
      sample: '2023-10-01T12:00:00Z'
    backend_id:
      description: Backend ID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    availability_zone:
      description: Optional availability group. Will be used for all instances provisioned in this tenant
      type: str
      returned: always
      sample: string-value
    internal_network_id:
      description: Internal network ID
      type: str
      returned: always
      sample: string-value
    external_network_id:
      description: External network ID
      type: str
      returned: always
      sample: string-value
    quotas:
      description: A list of quotas items.
      type: list
      returned: always
      sample: []
      contains:
        name:
          description: Name
          type: str
          returned: always
          sample: My-Awesome-Resource
        usage:
          description: Usage
          type: int
          returned: always
          sample: 123
        limit:
          description: Limit
          type: int
          returned: always
          sample: 123
    default_volume_type_name:
      description: Volume type name to use when creating volumes.
      type: str
      returned: always
      sample: string-value
    marketplace_offering_uuid:
      description: Marketplace offering UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    marketplace_offering_name:
      description: Marketplace offering name
      type: str
      returned: always
      sample: string-value
    marketplace_offering_plugin_options:
      description: Marketplace offering plugin options
      type: dict
      returned: always
      sample: {}
    marketplace_category_uuid:
      description: Marketplace category UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    marketplace_category_name:
      description: Marketplace category name
      type: str
      returned: always
      sample: string-value
    marketplace_resource_uuid:
      description: Marketplace resource UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    marketplace_plan_uuid:
      description: Marketplace plan UUID
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    marketplace_resource_state:
      description: Marketplace resource state
      type: str
      returned: always
      sample: string-value
    is_usage_based:
      description: Is usage based
      type: bool
      returned: always
      sample: true
    is_limit_based:
      description: Is limit based
      type: bool
      returned: always
      sample: true

"""

ARGUMENT_SPEC = {
    "access_token": {"type": "str", "required": True},
    "api_url": {"type": "str", "required": True},
    "state": {"type": "str", "required": False, "choices": ["present", "absent"]},
    "wait": {"type": "bool", "required": False},
    "timeout": {"type": "int", "required": False},
    "interval": {"type": "int", "required": False},
    "name": {"type": "str", "required": True},
    "project": {"type": "str", "required": True},
    "offering": {"type": "str", "required": True},
    "plan": {"type": "str", "required": False},
    "limits": {"type": "object", "required": False},
    "description": {"type": "str", "required": False},
    "subnet_cidr": {"type": "str", "required": False},
    "skip_connection_extnet": {"type": "bool", "required": False},
    "skip_creation_of_default_router": {"type": "bool", "required": False},
    "availability_zone": {"type": "str", "required": False},
}

RUNNER_CONTEXT = {
    "resource_type": "OpenStack tenant",
    "existence_check_url": "/api/openstack-tenants/",
    "existence_check_filter_keys": {"project": "project_uuid"},
    "update_url": None,
    "update_check_fields": [],
    "attribute_param_names": [
        "skip_connection_extnet",
        "skip_creation_of_default_router",
        "availability_zone",
        "description",
        "subnet_cidr",
        "name",
    ],
    "resolvers": {
        "offering": {
            "url": "/api/marketplace-public-offerings/",
            "error_message": None,
            "filter_by": [],
        },
        "project": {"url": "/api/projects/", "error_message": None, "filter_by": []},
    },
}


def main():
    """Main execution entrypoint for the Ansible module."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )
    runner = OrderRunner(module, RUNNER_CONTEXT)
    runner.run()


if __name__ == "__main__":
    main()
