#!/usr/bin/python
#
# THIS FILE IS AUTOGENERATED BY THE ANSIBLE MODULE GENERATOR - DO NOT EDIT
#
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.waldur.cloud.plugins.module_utils.waldur.crud_runner import (
    CrudResourceRunner,
)
from waldur_api_client.api.customers import customers_create
from waldur_api_client.api.customers import customers_destroy
from waldur_api_client.api.customers import customers_list
from waldur_api_client.models.customer_request import CustomerRequest

ANSIBLE_METADATA = {
    "metadata_version": "1.1",
    "status": ["preview"],
    "supported_by": "OpenNode",
}

DOCUMENTATION = """
---
module: waldur.cloud.customer
short_description: Manage Customers in Waldur.
version_added: '0.1'
description:
- Manage Customers in Waldur.
requirements:
- python = 3.11
- waldur-api-client
options:
  access_token:
    description: An access token.
    required: true
    type: str
  api_url:
    description: Fully qualified URL to the API.
    required: true
    type: str
  state:
    description: Should the resource be present or absent.
    choices:
    - present
    - absent
    type: str
    required: false
  name:
    type: str
    required: true
    description: The name of the customer to check/create/delete.
  backend_id:
    type: str
    required: false
    description: Organization identifier in another application.
  image:
    type: str
    required: false
    description: ''
  native_name:
    type: str
    required: false
    description: ''
  abbreviation:
    type: str
    required: false
    description: ''
  contact_details:
    type: str
    required: false
    description: ''
  email:
    type: str
    required: false
    description: ''
  phone_number:
    type: str
    required: false
    description: ''
  registration_code:
    type: str
    required: false
    description: ''
  homepage:
    type: str
    required: false
    description: ''
  vat_code:
    type: str
    required: false
    description: VAT number
  postal:
    type: str
    required: false
    description: ''
  address:
    type: str
    required: false
    description: ''
  bank_name:
    type: str
    required: false
    description: ''
  latitude:
    type: float
    required: false
    description: ''
  longitude:
    type: float
    required: false
    description: ''
  bank_account:
    type: str
    required: false
    description: ''
  country:
    type: str
    required: false
    description: ''
    choices:
    - AL
    - AT
    - BE
    - BG
    - BA
    - CH
    - CY
    - CZ
    - DE
    - DK
    - ES
    - EE
    - FI
    - FR
    - GB
    - GE
    - GR
    - HR
    - HU
    - IE
    - IS
    - IT
    - LT
    - LU
    - LV
    - MC
    - MK
    - MT
    - NL
    - 'NO'
    - PL
    - PT
    - RO
    - RS
    - SK
    - SI
    - SE
    - UA
    - EU
    - ''

"""

EXAMPLES = """
- name: Create a new customer.
  hosts: localhost
  tasks:
  - name: Add customer
    waldur.cloud.customer:
      access_token: some_value
      api_url: some_value
      state: present
      name: My Awesome Customer
- name: Remove an existing customer.
  hosts: localhost
  tasks:
  - name: Remove customer
    waldur.cloud.customer:
      access_token: b83557fd8e2066e98f27dee8f3b3433cdc4183ce
      api_url: https://waldur.example.com:8000/api
      state: absent
      name: My Awesome Customer

"""

RETURN = """
resource:
  description: The state of the customer after the operation.
  type: dict
  returned: on success
  contains:
    url:
      description: url
      type: str
      returned: always
      sample: https://api.example.com/api/resource/...
    uuid:
      description: uuid
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    created:
      description: created
      type: str
      returned: always
      sample: '2023-10-01T12:00:00Z'
    organization_groups:
      description: organization groups
      type: list
      returned: always
      sample: null
      contains:
        uuid:
          description: uuid
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        url:
          description: url
          type: str
          returned: always
          sample: https://api.example.com/api/resource/...
        name:
          description: name
          type: str
          returned: always
          sample: string_value
        parent_uuid:
          description: parent uuid
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        parent_name:
          description: parent name
          type: str
          returned: always
          sample: string_value
        parent:
          description: parent
          type: str
          returned: always
          sample: https://api.example.com/api/resource/...
        customers_count:
          description: customers count
          type: int
          returned: always
          sample: 123
    display_name:
      description: display name
      type: str
      returned: always
      sample: string_value
    backend_id:
      description: Organization identifier in another application.
      type: str
      returned: always
      sample: string_value
    image:
      description: image
      type: str
      returned: always
      sample: https://api.example.com/api/resource/...
    blocked:
      description: blocked
      type: bool
      returned: always
      sample: true
    archived:
      description: archived
      type: bool
      returned: always
      sample: true
    default_tax_percent:
      description: default tax percent
      type: str
      returned: always
      sample: '123.45'
    accounting_start_date:
      description: accounting start date
      type: str
      returned: always
      sample: '2023-10-01T12:00:00Z'
    projects_count:
      description: projects count
      type: int
      returned: always
      sample: 123
    users_count:
      description: users count
      type: int
      returned: always
      sample: 123
    sponsor_number:
      description: External ID of the sponsor covering the costs
      type: int
      returned: always
      sample: 123
    country_name:
      description: country name
      type: str
      returned: always
      sample: string_value
    max_service_accounts:
      description: Maximum number of service accounts allowed
      type: int
      returned: always
      sample: 123
    name:
      description: name
      type: str
      returned: always
      sample: string_value
    slug:
      description: slug
      type: str
      returned: always
      sample: string_value
    native_name:
      description: native name
      type: str
      returned: always
      sample: string_value
    abbreviation:
      description: abbreviation
      type: str
      returned: always
      sample: string_value
    contact_details:
      description: contact details
      type: str
      returned: always
      sample: string_value
    agreement_number:
      description: agreement number
      type: str
      returned: always
      sample: string_value
    email:
      description: email
      type: str
      returned: always
      sample: alice@gmail.com
    phone_number:
      description: phone number
      type: str
      returned: always
      sample: string_value
    access_subnets:
      description: Enter a comma separated list of IPv4 or IPv6 CIDR addresses from where connection to self-service is allowed.
      type: str
      returned: always
      sample: string_value
    registration_code:
      description: registration code
      type: str
      returned: always
      sample: string_value
    homepage:
      description: homepage
      type: str
      returned: always
      sample: https://api.example.com/api/resource/...
    domain:
      description: domain
      type: str
      returned: always
      sample: string_value
    vat_code:
      description: VAT number
      type: str
      returned: always
      sample: string_value
    postal:
      description: postal
      type: str
      returned: always
      sample: string_value
    address:
      description: address
      type: str
      returned: always
      sample: string_value
    bank_name:
      description: bank name
      type: str
      returned: always
      sample: string_value
    latitude:
      description: latitude
      type: float
      returned: always
      sample: 123.45
    longitude:
      description: longitude
      type: float
      returned: always
      sample: 123.45
    bank_account:
      description: bank account
      type: str
      returned: always
      sample: string_value
    country:
      description: country
      type: str
      returned: always
      sample: null
    payment_profiles:
      description: payment profiles
      type: list
      returned: always
      sample: null
      contains:
        uuid:
          description: uuid
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        url:
          description: url
          type: str
          returned: always
          sample: https://api.example.com/api/resource/...
        name:
          description: name
          type: str
          returned: always
          sample: string_value
        organization_uuid:
          description: organization uuid
          type: str
          returned: always
          sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        organization:
          description: organization
          type: str
          returned: always
          sample: https://api.example.com/api/resource/...
        attributes:
          description: ''
          type: dict
          returned: always
          sample: null
          contains:
            end_date:
              description: end date
              type: str
              returned: always
              sample: string_value
            agreement_number:
              description: agreement number
              type: str
              returned: always
              sample: string_value
            contract_sum:
              description: contract sum
              type: int
              returned: always
              sample: 123
        payment_type:
          description: ''
          type: str
          returned: always
          sample: string_value
        payment_type_display:
          description: payment type display
          type: str
          returned: always
          sample: string_value
        is_active:
          description: is active
          type: bool
          returned: always
          sample: true
    customer_credit:
      description: customer credit
      type: float
      returned: always
      sample: 123.45
    customer_unallocated_credit:
      description: customer unallocated credit
      type: float
      returned: always
      sample: 123.45
    is_service_provider:
      description: is service provider
      type: bool
      returned: always
      sample: true
    service_provider:
      description: service provider
      type: str
      returned: always
      sample: https://api.example.com/api/resource/...
    service_provider_uuid:
      description: service provider uuid
      type: str
      returned: always
      sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    call_managing_organization_uuid:
      description: call managing organization uuid
      type: str
      returned: always
      sample: string_value
    billing_price_estimate:
      description: ''
      type: dict
      returned: always
      sample: null
      contains:
        total:
          description: total
          type: str
          returned: always
          sample: '123.45'
        current:
          description: current
          type: str
          returned: always
          sample: '123.45'
        tax:
          description: tax
          type: str
          returned: always
          sample: '123.45'
        tax_current:
          description: tax current
          type: str
          returned: always
          sample: '123.45'

"""

ARGUMENT_SPEC = {
    "access_token": {"type": "str", "required": True},
    "api_url": {"type": "str", "required": True},
    "state": {"type": "str", "required": False, "choices": ["present", "absent"]},
    "name": {"type": "str", "required": True},
    "backend_id": {"type": "str", "required": False},
    "image": {"type": "str", "required": False},
    "native_name": {"type": "str", "required": False},
    "abbreviation": {"type": "str", "required": False},
    "contact_details": {"type": "str", "required": False},
    "email": {"type": "str", "required": False},
    "phone_number": {"type": "str", "required": False},
    "registration_code": {"type": "str", "required": False},
    "homepage": {"type": "str", "required": False},
    "vat_code": {"type": "str", "required": False},
    "postal": {"type": "str", "required": False},
    "address": {"type": "str", "required": False},
    "bank_name": {"type": "str", "required": False},
    "latitude": {"type": "float", "required": False},
    "longitude": {"type": "float", "required": False},
    "bank_account": {"type": "str", "required": False},
    "country": {
        "type": "str",
        "required": False,
        "choices": [
            "AL",
            "AT",
            "BE",
            "BG",
            "BA",
            "CH",
            "CY",
            "CZ",
            "DE",
            "DK",
            "ES",
            "EE",
            "FI",
            "FR",
            "GB",
            "GE",
            "GR",
            "HR",
            "HU",
            "IE",
            "IS",
            "IT",
            "LT",
            "LU",
            "LV",
            "MC",
            "MK",
            "MT",
            "NL",
            "NO",
            "PL",
            "PT",
            "RO",
            "RS",
            "SK",
            "SI",
            "SE",
            "UA",
            "EU",
            "",
        ],
    },
}

RUNNER_CONTEXT = {
    "resource_type": "customer",
    "existence_check_func": customers_list,
    "present_create_func": customers_create,
    "present_create_model_class": CustomerRequest,
    "absent_destroy_func": customers_destroy,
    "absent_destroy_path_param": "uuid",
    "model_param_names": [
        "backend_id",
        "image",
        "name",
        "native_name",
        "abbreviation",
        "contact_details",
        "email",
        "phone_number",
        "registration_code",
        "homepage",
        "vat_code",
        "postal",
        "address",
        "bank_name",
        "latitude",
        "longitude",
        "bank_account",
        "country",
    ],
    "resolvers": {},
}


def main():
    """Main execution entrypoint for the Ansible module."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )
    runner = CrudResourceRunner(module, RUNNER_CONTEXT)
    runner.run()


if __name__ == "__main__":
    main()
