#!/usr/bin/python
#
# THIS FILE IS AUTOGENERATED BY THE ANSIBLE MODULE GENERATOR - DO NOT EDIT
#
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.waldur.cloud.plugins.module_utils.waldur.facts_runner import (
    FactsRunner,
)
from waldur_api_client.api.openstack_security_groups import (
    openstack_security_groups_list,
)
from waldur_api_client.api.openstack_security_groups import (
    openstack_security_groups_retrieve,
)
from waldur_api_client.api.openstack_tenants import openstack_tenants_list
from waldur_api_client.api.openstack_tenants import openstack_tenants_retrieve
from waldur_api_client.api.projects import projects_list
from waldur_api_client.api.projects import projects_retrieve

ANSIBLE_METADATA = {
    "metadata_version": "1.1",
    "status": ["preview"],
    "supported_by": "OpenNode",
}

DOCUMENTATION = """
---
module: waldur.cloud.openstack_security_group
short_description: Get an existing security group.
version_added: '0.1'
description:
- Get an existing security group.
requirements:
- python = 3.11
- waldur-api-client
options:
  access_token:
    description: An access token.
    required: true
    type: str
    no_log: true
  api_url:
    description: Fully qualified URL to the API.
    required: true
    type: str
  name:
    type: str
    required: false
    description: The name or UUID of the security group.
  project:
    type: str
    required: false
    description: The name or UUID of the project.
  tenant:
    type: str
    required: false

"""

EXAMPLES = """
- name: Get a security group facts
  hosts: localhost
  tasks:
  - name: Get a security group
    waldur.cloud.openstack_security_group:
      access_token: b83557fd8e2066e98f27dee8f3b3433cdc4183ce
      api_url: https://waldur.example.com:8000/api
      name: Security_group Name or UUID
      project: Project Name or UUID
      tenant: some_value

"""

RETURN = """
resource:
  description: A list of dictionaries describing the found security_groups.
  type: list
  returned: on success
  elements: dict
  contains:
    description: A dictionary describing a single security_group.
    type: dict
    returned: always
    contains:
      url:
        description: url
        type: str
        returned: always
        sample: https://api.example.com/api/resource/...
      uuid:
        description: uuid
        type: str
        returned: always
        sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
      name:
        description: name
        type: str
        returned: always
        sample: string_value
      description:
        description: description
        type: str
        returned: always
        sample: string_value
      service_name:
        description: service name
        type: str
        returned: always
        sample: string_value
      service_settings:
        description: service settings
        type: str
        returned: always
        sample: https://api.example.com/api/resource/...
      service_settings_uuid:
        description: service settings uuid
        type: str
        returned: always
        sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
      service_settings_state:
        description: service settings state
        type: str
        returned: always
        sample: string_value
      service_settings_error_message:
        description: service settings error message
        type: str
        returned: always
        sample: string_value
      project:
        description: project
        type: str
        returned: always
        sample: https://api.example.com/api/resource/...
      project_name:
        description: project name
        type: str
        returned: always
        sample: string_value
      project_uuid:
        description: project uuid
        type: str
        returned: always
        sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
      customer:
        description: customer
        type: str
        returned: always
        sample: https://api.example.com/api/resource/...
      customer_name:
        description: customer name
        type: str
        returned: always
        sample: string_value
      customer_native_name:
        description: customer native name
        type: str
        returned: always
        sample: string_value
      customer_abbreviation:
        description: customer abbreviation
        type: str
        returned: always
        sample: string_value
      error_message:
        description: error message
        type: str
        returned: always
        sample: string_value
      error_traceback:
        description: error traceback
        type: str
        returned: always
        sample: string_value
      resource_type:
        description: resource type
        type: str
        returned: always
        sample: string_value
      state:
        description: ''
        type: str
        returned: always
        sample: string_value
      created:
        description: created
        type: str
        returned: always
        sample: '2023-10-01T12:00:00Z'
      modified:
        description: modified
        type: str
        returned: always
        sample: '2023-10-01T12:00:00Z'
      backend_id:
        description: backend id
        type: str
        returned: always
        sample: string_value
      access_url:
        description: access url
        type: str
        returned: always
        sample: string_value
      tenant:
        description: tenant
        type: str
        returned: always
        sample: https://api.example.com/api/resource/...
      tenant_name:
        description: tenant name
        type: str
        returned: always
        sample: string_value
      tenant_uuid:
        description: tenant uuid
        type: str
        returned: always
        sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
      rules:
        description: rules
        type: list
        returned: always
        sample: null
        contains:
          ethertype:
            description: ''
            type: str
            returned: always
            sample: string_value
          direction:
            description: ''
            type: str
            returned: always
            sample: string_value
          protocol:
            description: protocol
            type: str
            returned: always
            sample: null
          from_port:
            description: from port
            type: int
            returned: always
            sample: 123
          to_port:
            description: to port
            type: int
            returned: always
            sample: 123
          cidr:
            description: cidr
            type: str
            returned: always
            sample: string_value
          description:
            description: description
            type: str
            returned: always
            sample: string_value
          remote_group_name:
            description: remote group name
            type: str
            returned: always
            sample: string_value
          remote_group_uuid:
            description: remote group uuid
            type: str
            returned: always
            sample: a1b2c3d4-e5f6-7890-abcd-ef1234567890
          id:
            description: id
            type: int
            returned: always
            sample: 123
          remote_group:
            description: remote group
            type: str
            returned: always
            sample: https://api.example.com/api/resource/...
      marketplace_offering_uuid:
        description: marketplace offering uuid
        type: str
        returned: always
        sample: string_value
      marketplace_offering_name:
        description: marketplace offering name
        type: str
        returned: always
        sample: string_value
      marketplace_offering_plugin_options:
        description: marketplace offering plugin options
        type: dict
        returned: always
        sample: null
      marketplace_category_uuid:
        description: marketplace category uuid
        type: str
        returned: always
        sample: string_value
      marketplace_category_name:
        description: marketplace category name
        type: str
        returned: always
        sample: string_value
      marketplace_resource_uuid:
        description: marketplace resource uuid
        type: str
        returned: always
        sample: string_value
      marketplace_plan_uuid:
        description: marketplace plan uuid
        type: str
        returned: always
        sample: string_value
      marketplace_resource_state:
        description: marketplace resource state
        type: str
        returned: always
        sample: string_value
      is_usage_based:
        description: is usage based
        type: bool
        returned: always
        sample: true
      is_limit_based:
        description: is limit based
        type: bool
        returned: always
        sample: true

"""

ARGUMENT_SPEC = {
    "access_token": {
        "description": "An access token.",
        "required": True,
        "type": "str",
        "no_log": True,
    },
    "api_url": {
        "description": "Fully qualified URL to the API.",
        "required": True,
        "type": "str",
    },
    "name": {"type": "str", "required": False},
    "project": {"type": "str", "required": False},
    "tenant": {"type": "str", "required": False},
}

RUNNER_CONTEXT = {
    "module_type": "facts",
    "resource_type": "security_group",
    "list_func": openstack_security_groups_list,
    "retrieve_func": openstack_security_groups_retrieve,
    "identifier_param": "name",
    "context_resolvers": {
        "project": {
            "list_func": projects_list,
            "retrieve_func": projects_retrieve,
            "error_message": "Project '{value}' not found.",
            "filter_key": "project_uuid",
        },
        "tenant": {
            "list_func": openstack_tenants_list,
            "retrieve_func": openstack_tenants_retrieve,
            "error_message": "Tenant '{value}' not found.",
            "filter_key": "tenant_uuid",
        },
    },
}


def main():
    """Main execution entrypoint for the Ansible module."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )
    runner = FactsRunner(module, RUNNER_CONTEXT)
    runner.run()


if __name__ == "__main__":
    main()
